#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{


    /// <summary>
    /// Status of the Configuration Question
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum KTR_ConfigurationQuestion_StateCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Active", 0)]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Inactive", 1)]
        Inactive = 1,
    }

    /// <summary>
    /// Reason for the status of the Configuration Question
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum KTR_ConfigurationQuestion_StatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Active", 2, "#0000ff")]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Draft", 0, "#00ff00")]
        Draft = 847610001,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Inactive", 1, "#ff0000")]
        Inactive = 2,
    }

    /// <summary>
    /// Defines configuration questions to be used to determine which modules and questions must be associated to a product template.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ktr_configurationquestion")]
    public partial class KTR_ConfigurationQuestion : Microsoft.Xrm.Sdk.Entity
    {

        /// <summary>
        /// Available fields, a the time of codegen, for the ktr_configurationquestion entity
        /// </summary>
        public partial class Fields
        {
            public const string CreatedBy = "createdby";
            public const string CreatedByName = "createdbyname";
            public const string CreatedByYomiName = "createdbyyominame";
            public const string CreatedOn = "createdon";
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
            public const string ImportSequenceNumber = "importsequencenumber";
            public const string KTR_ConfigurationQuestion_ConfigurationAnswer = "KTR_ConfigurationQuestion_ConfigurationAnswer";
            public const string KTR_ConfigurationQuestion_DependencyRule = "KTR_ConfigurationQuestion_DependencyRule";
            public const string KTR_ConfigurationQuestionId = "ktr_configurationquestionid";
            public const string Id = "ktr_configurationquestionid";
            public const string KTR_DependencyRuleAnswer_ConfigurationQuestion_KTR_ConfigurationQuestion = "KTR_DependencyRuleAnswer_ConfigurationQuestion_KTR_ConfigurationQuestion";
            public const string KTR_Name = "ktr_name";
            public const string KTR_ProductConfigQuestion_ConfigurationQuestion_KTR_ConfigurationQuestion = "KTR_ProductConfigQuestion_ConfigurationQuestion_KTR_ConfigurationQuestion";
            public const string KTR_ProjectProductConfig_ConfigurationQuestion = "KTR_ProjectProductConfig_ConfigurationQuestion";
            public const string KTR_ProjectProductConfigQuestionAnswer_ConfigurationQuestion_KTR_ConfigurationQuestion = "KTR_ProjectProductConfigQuestionAnswer_ConfigurationQuestion_KTR_ConfigurationQuestion";
            public const string KTR_Rule = "ktr_rule";
            public const string KTR_RuleName = "ktr_rulename";
            public const string ModifiedBy = "modifiedby";
            public const string ModifiedByName = "modifiedbyname";
            public const string ModifiedByYomiName = "modifiedbyyominame";
            public const string ModifiedOn = "modifiedon";
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
            public const string OverriddenCreatedOn = "overriddencreatedon";
            public const string OwnerId = "ownerid";
            public const string OwnerIdName = "owneridname";
            public const string OwnerIdYomiName = "owneridyominame";
            public const string OwningBusinessUnit = "owningbusinessunit";
            public const string OwningBusinessUnitName = "owningbusinessunitname";
            public const string OwningTeam = "owningteam";
            public const string OwningUser = "owninguser";
            public const string StateCode = "statecode";
            public const string StateCodename = "statecodename";
            public const string StatusCode = "statuscode";
            public const string StatusCodename = "statuscodename";
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
            public const string VersionNumber = "versionnumber";
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ConfigurationQuestion(System.Guid id) :
                base(EntityLogicalName, id)
        {
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ConfigurationQuestion(string keyName, object keyValue) :
                base(EntityLogicalName, keyName, keyValue)
        {
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ConfigurationQuestion(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) :
                base(EntityLogicalName, keyAttributes)
        {
        }

        /// <summary>
        /// Default Constructor.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ConfigurationQuestion() :
                base(EntityLogicalName)
        {
        }

        public const string PrimaryIdAttribute = "ktr_configurationquestionid";

        public const string PrimaryNameAttribute = "ktr_name";

        public const string EntitySchemaName = "ktr_ConfigurationQuestion";

        public const string EntityLogicalName = "ktr_configurationquestion";

        public const string EntityLogicalCollectionName = "ktr_configurationquestions";

        public const string EntitySetName = "ktr_configurationquestions";

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
        public string CreatedByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdby"))
                {
                    return this.FormattedValues["createdby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
        public string CreatedByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdby"))
                {
                    return this.FormattedValues["createdby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("createdonbehalfby", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
        public string CreatedOnBehalfByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdonbehalfby"))
                {
                    return this.FormattedValues["createdonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
        public string CreatedOnBehalfByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdonbehalfby"))
                {
                    return this.FormattedValues["createdonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_configurationquestionid")]
        public System.Nullable<System.Guid> KTR_ConfigurationQuestionId
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("ktr_configurationquestionid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_configurationquestionid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_configurationquestionid")]
        public override System.Guid Id
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return base.Id;
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.KTR_ConfigurationQuestionId = value;
            }
        }

        /// <summary>
        /// The config question to be asked
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_name")]
        public string KTR_Name
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<string>("ktr_name");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_name", value);
            }
        }

        /// <summary>
        /// Field indicating if a single Answer or multiple Answers can be added to the Project Product Config
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_rule")]
        public virtual KTR_Rule? KTR_Rule
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_Rule?)(EntityOptionSetEnum.GetEnum(this, "ktr_rule")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_rule", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_rulename")]
        public string KTR_RuleName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_rule"))
                {
                    return this.FormattedValues["ktr_rule"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
        public string ModifiedByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedby"))
                {
                    return this.FormattedValues["modifiedby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
        public string ModifiedByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedby"))
                {
                    return this.FormattedValues["modifiedby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("modifiedonbehalfby", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
        public string ModifiedOnBehalfByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedonbehalfby"))
                {
                    return this.FormattedValues["modifiedonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
        public string ModifiedOnBehalfByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedonbehalfby"))
                {
                    return this.FormattedValues["modifiedonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ownerid", value);
            }
        }

        /// <summary>
        /// Name of the owner
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
        public string OwnerIdName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ownerid"))
                {
                    return this.FormattedValues["ownerid"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Yomi name of the owner
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
        public string OwnerIdYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ownerid"))
                {
                    return this.FormattedValues["ownerid"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
        public string OwningBusinessUnitName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("owningbusinessunit"))
                {
                    return this.FormattedValues["owningbusinessunit"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Configuration Question
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public virtual KTR_ConfigurationQuestion_StateCode? StateCode
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_ConfigurationQuestion_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
        public string StateCodename
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("statecode"))
                {
                    return this.FormattedValues["statecode"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Reason for the status of the Configuration Question
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public virtual KTR_ConfigurationQuestion_StatusCode? StatusCode
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_ConfigurationQuestion_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
        public string StatusCodename
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("statuscode"))
                {
                    return this.FormattedValues["statuscode"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UtcConversionTimeZoneCode
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N ktr_ConfigurationQuestion_ConfigurationAnswer
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_ConfigurationQuestion_ConfigurationAnswer")]
        public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KTR_ConfigurationAnswer> KTR_ConfigurationQuestion_ConfigurationAnswer
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ConfigurationAnswer>("ktr_ConfigurationQuestion_ConfigurationAnswer", null);
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ConfigurationAnswer>("ktr_ConfigurationQuestion_ConfigurationAnswer", null, value);
            }
        }

        /// <summary>
        /// 1:N ktr_ConfigurationQuestion_DependencyRule
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_ConfigurationQuestion_DependencyRule")]
        public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KTR_DependencyRule> KTR_ConfigurationQuestion_DependencyRule
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_DependencyRule>("ktr_ConfigurationQuestion_DependencyRule", null);
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_DependencyRule>("ktr_ConfigurationQuestion_DependencyRule", null, value);
            }
        }

        /// <summary>
        /// 1:N ktr_dependencyruleanswer_ConfigurationQuestion_ktr_configurationquestion
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_dependencyruleanswer_ConfigurationQuestion_ktr_configurationquestion")]
        public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KTR_DependencyRuleAnswer> KTR_DependencyRuleAnswer_ConfigurationQuestion_KTR_ConfigurationQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_DependencyRuleAnswer>("ktr_dependencyruleanswer_ConfigurationQuestion_ktr_configurationquestion", null);
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_DependencyRuleAnswer>("ktr_dependencyruleanswer_ConfigurationQuestion_ktr_configurationquestion", null, value);
            }
        }

        /// <summary>
        /// 1:N ktr_productconfigquestion_ConfigurationQuestion_ktr_configurationquestion
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_productconfigquestion_ConfigurationQuestion_ktr_configurationquestion")]
        public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KTR_ProductConfigQuestion> KTR_ProductConfigQuestion_ConfigurationQuestion_KTR_ConfigurationQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ProductConfigQuestion>("ktr_productconfigquestion_ConfigurationQuestion_ktr_configurationquestion", null);
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ProductConfigQuestion>("ktr_productconfigquestion_ConfigurationQuestion_ktr_configurationquestion", null, value);
            }
        }

        /// <summary>
        /// 1:N ktr_ProjectProductConfig_ConfigurationQuestion
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_ProjectProductConfig_ConfigurationQuestion")]
        public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KTR_ProjectProductConfig> KTR_ProjectProductConfig_ConfigurationQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ProjectProductConfig>("ktr_ProjectProductConfig_ConfigurationQuestion", null);
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ProjectProductConfig>("ktr_ProjectProductConfig_ConfigurationQuestion", null, value);
            }
        }

        /// <summary>
        /// 1:N ktr_projectproductconfigquestionanswer_ConfigurationQuestion_ktr_configurationquestion
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_projectproductconfigquestionanswer_ConfigurationQuestion_ktr_configurationque" +
            "stion")]
        public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KTR_ProjectProductConfigQuestionAnswer> KTR_ProjectProductConfigQuestionAnswer_ConfigurationQuestion_KTR_ConfigurationQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ProjectProductConfigQuestionAnswer>("ktr_projectproductconfigquestionanswer_ConfigurationQuestion_ktr_configurationque" +
                        "stion", null);
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KTR_ProjectProductConfigQuestionAnswer>("ktr_projectproductconfigquestionanswer_ConfigurationQuestion_ktr_configurationque" +
                        "stion", null, value);
            }
        }

        /// <summary>
        /// Constructor for populating via LINQ queries given a LINQ anonymous type
        /// <param name="anonymousType">LINQ anonymous type.</param>
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ConfigurationQuestion(object anonymousType) :
                this()
        {
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();

                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int)value);
                    name = name.Remove(name.Length - "enum".Length);
                }

                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ktr_configurationquestionid"] = base.Id;
                        break;
                    case "ktr_configurationquestionid":
                        var id = (System.Nullable<System.Guid>)value;
                        if (id == null) { continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
        }
    }
}
#pragma warning restore CS1591
