#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{


    /// <summary>
    /// Status of the Product Config Question Display Rule
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum KTR_ProductConfigQuestionDisplayRule_StateCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Active", 0, null, null, null, 1033, "Active")]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Inactive", 1, null, null, null, 1033, "Inactive")]
        Inactive = 1,
    }

    /// <summary>
    /// Reason for the status of the Product Config Question Display Rule
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum KTR_ProductConfigQuestionDisplayRule_StatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Active", 0, null, null, null, 1033, "Active")]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Inactive", 1, null, null, null, 1033, "Inactive")]
        Inactive = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ktr_productconfigquestiondisplayrule")]
    public partial class KTR_ProductConfigQuestionDisplayRule : Microsoft.Xrm.Sdk.Entity
    {

        /// <summary>
        /// Available fields, a the time of codegen, for the ktr_productconfigquestiondisplayrule entity
        /// </summary>
        public partial class Fields
        {
            public const string CreatedBy = "createdby";
            public const string CreatedByName = "createdbyname";
            public const string CreatedByYomiName = "createdbyyominame";
            public const string CreatedOn = "createdon";
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
            public const string ImportSequenceNumber = "importsequencenumber";
            public const string KTR_DisplaySettings = "ktr_displaysettings";
            public const string KTR_DisplaySettingsName = "ktr_displaysettingsname";
            public const string KTR_Id = "ktr_id";
            public const string KTR_ImpactedConfigAnswer = "ktr_impactedconfiganswer";
            public const string KTR_ImpactedConfigAnswerName = "ktr_impactedconfiganswername";
            public const string KTR_ImpactedConfigQuestion = "ktr_impactedconfigquestion";
            public const string KTR_ImpactedConfigQuestionName = "ktr_impactedconfigquestionname";
            public const string KTR_ProductConfigQuestion = "ktr_productconfigquestion";
            public const string KTR_ProductConfigQuestionDisplayRuleId = "ktr_productconfigquestiondisplayruleid";
            public const string Id = "ktr_productconfigquestiondisplayruleid";
            public const string KTR_ProductConfigQuestionName = "ktr_productconfigquestionname";
            public const string KTR_RuleConfigAnswer = "ktr_ruleconfiganswer";
            public const string KTR_RuleConfigAnswerName = "ktr_ruleconfiganswername";
            public const string KTR_RuleConfigQuestion = "ktr_ruleconfigquestion";
            public const string KTR_RuleConfigQuestionName = "ktr_ruleconfigquestionname";
            public const string KTR_Type = "ktr_type";
            public const string KTR_TypeName = "ktr_typename";
            public const string ModifiedBy = "modifiedby";
            public const string ModifiedByName = "modifiedbyname";
            public const string ModifiedByYomiName = "modifiedbyyominame";
            public const string ModifiedOn = "modifiedon";
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
            public const string OverriddenCreatedOn = "overriddencreatedon";
            public const string OwnerId = "ownerid";
            public const string OwnerIdName = "owneridname";
            public const string OwnerIdYomiName = "owneridyominame";
            public const string OwningBusinessUnit = "owningbusinessunit";
            public const string OwningBusinessUnitName = "owningbusinessunitname";
            public const string OwningTeam = "owningteam";
            public const string OwningUser = "owninguser";
            public const string StateCode = "statecode";
            public const string StateCodename = "statecodename";
            public const string StatusCode = "statuscode";
            public const string StatusCodename = "statuscodename";
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
            public const string VersionNumber = "versionnumber";
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ProductConfigQuestionDisplayRule(System.Guid id) :
                base(EntityLogicalName, id)
        {
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ProductConfigQuestionDisplayRule(string keyName, object keyValue) :
                base(EntityLogicalName, keyName, keyValue)
        {
        }

        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ProductConfigQuestionDisplayRule(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) :
                base(EntityLogicalName, keyAttributes)
        {
        }

        /// <summary>
        /// Default Constructor.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ProductConfigQuestionDisplayRule() :
                base(EntityLogicalName)
        {
        }

        public const string PrimaryIdAttribute = "ktr_productconfigquestiondisplayruleid";

        public const string PrimaryNameAttribute = "ktr_id";

        public const string EntitySchemaName = "ktr_ProductConfigQuestionDisplayRule";

        public const string EntityLogicalName = "ktr_productconfigquestiondisplayrule";

        public const string EntityLogicalCollectionName = "ktr_productconfigquestiondisplayrules";

        public const string EntitySetName = "ktr_productconfigquestiondisplayrules";

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
        public string CreatedByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdby"))
                {
                    return this.FormattedValues["createdby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
        public string CreatedByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdby"))
                {
                    return this.FormattedValues["createdby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("createdonbehalfby", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
        public string CreatedOnBehalfByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdonbehalfby"))
                {
                    return this.FormattedValues["createdonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
        public string CreatedOnBehalfByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("createdonbehalfby"))
                {
                    return this.FormattedValues["createdonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("importsequencenumber", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_displaysettings")]
        public virtual KTR_DisplayRuleSetting? KTR_DisplaySettings
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_DisplayRuleSetting?)(EntityOptionSetEnum.GetEnum(this, "ktr_displaysettings")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_displaysettings", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_displaysettingsname")]
        public string KTR_DisplaySettingsName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_displaysettings"))
                {
                    return this.FormattedValues["ktr_displaysettings"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_id")]
        public string KTR_Id
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<string>("ktr_id");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_id", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_impactedconfiganswer")]
        public Microsoft.Xrm.Sdk.EntityReference KTR_ImpactedConfigAnswer
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ktr_impactedconfiganswer");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_impactedconfiganswer", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_impactedconfiganswername")]
        public string KTR_ImpactedConfigAnswerName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_impactedconfiganswer"))
                {
                    return this.FormattedValues["ktr_impactedconfiganswer"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_impactedconfigquestion")]
        public Microsoft.Xrm.Sdk.EntityReference KTR_ImpactedConfigQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ktr_impactedconfigquestion");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_impactedconfigquestion", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_impactedconfigquestionname")]
        public string KTR_ImpactedConfigQuestionName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_impactedconfigquestion"))
                {
                    return this.FormattedValues["ktr_impactedconfigquestion"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_productconfigquestion")]
        public Microsoft.Xrm.Sdk.EntityReference KTR_ProductConfigQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ktr_productconfigquestion");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_productconfigquestion", value);
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_productconfigquestiondisplayruleid")]
        public System.Nullable<System.Guid> KTR_ProductConfigQuestionDisplayRuleId
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("ktr_productconfigquestiondisplayruleid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_productconfigquestiondisplayruleid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_productconfigquestiondisplayruleid")]
        public override System.Guid Id
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return base.Id;
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.KTR_ProductConfigQuestionDisplayRuleId = value;
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_productconfigquestionname")]
        public string KTR_ProductConfigQuestionName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_productconfigquestion"))
                {
                    return this.FormattedValues["ktr_productconfigquestion"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_ruleconfiganswer")]
        public Microsoft.Xrm.Sdk.EntityReference KTR_RuleConfigAnswer
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ktr_ruleconfiganswer");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_ruleconfiganswer", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_ruleconfiganswername")]
        public string KTR_RuleConfigAnswerName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_ruleconfiganswer"))
                {
                    return this.FormattedValues["ktr_ruleconfiganswer"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_ruleconfigquestion")]
        public Microsoft.Xrm.Sdk.EntityReference KTR_RuleConfigQuestion
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ktr_ruleconfigquestion");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_ruleconfigquestion", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_ruleconfigquestionname")]
        public string KTR_RuleConfigQuestionName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_ruleconfigquestion"))
                {
                    return this.FormattedValues["ktr_ruleconfigquestion"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_type")]
        public virtual KTR_DisplayRuleType? KTR_Type
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_DisplayRuleType?)(EntityOptionSetEnum.GetEnum(this, "ktr_type")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ktr_type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_typename")]
        public string KTR_TypeName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ktr_type"))
                {
                    return this.FormattedValues["ktr_type"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
        public string ModifiedByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedby"))
                {
                    return this.FormattedValues["modifiedby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
        public string ModifiedByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedby"))
                {
                    return this.FormattedValues["modifiedby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("modifiedonbehalfby", value);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
        public string ModifiedOnBehalfByName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedonbehalfby"))
                {
                    return this.FormattedValues["modifiedonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
        public string ModifiedOnBehalfByYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("modifiedonbehalfby"))
                {
                    return this.FormattedValues["modifiedonbehalfby"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("overriddencreatedon", value);
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("ownerid", value);
            }
        }

        /// <summary>
        /// Name of the owner
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
        public string OwnerIdName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ownerid"))
                {
                    return this.FormattedValues["ownerid"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Yomi name of the owner
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
        public string OwnerIdYomiName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("ownerid"))
                {
                    return this.FormattedValues["ownerid"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
        public string OwningBusinessUnitName
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("owningbusinessunit"))
                {
                    return this.FormattedValues["owningbusinessunit"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Product Config Question Display Rule
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public virtual KTR_ProductConfigQuestionDisplayRule_StateCode? StateCode
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_ProductConfigQuestionDisplayRule_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
        public string StateCodename
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("statecode"))
                {
                    return this.FormattedValues["statecode"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// Reason for the status of the Product Config Question Display Rule
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public virtual KTR_ProductConfigQuestionDisplayRule_StatusCode? StatusCode
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return ((KTR_ProductConfigQuestionDisplayRule_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
        public string StatusCodename
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                if (this.FormattedValues.Contains("statuscode"))
                {
                    return this.FormattedValues["statuscode"];
                }
                else
                {
                    return default(string);
                }
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("timezoneruleversionnumber", value);
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UtcConversionTimeZoneCode
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            [System.Diagnostics.DebuggerNonUserCode()]
            set
            {
                this.SetAttributeValue("utcconversiontimezonecode", value);
            }
        }

        /// <summary>
        /// Version Number
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            [System.Diagnostics.DebuggerNonUserCode()]
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// Constructor for populating via LINQ queries given a LINQ anonymous type
        /// <param name="anonymousType">LINQ anonymous type.</param>
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode()]
        public KTR_ProductConfigQuestionDisplayRule(object anonymousType) :
                this()
        {
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();

                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int)value);
                    name = name.Remove(name.Length - "enum".Length);
                }

                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ktr_productconfigquestiondisplayruleid"] = base.Id;
                        break;
                    case "ktr_productconfigquestiondisplayruleid":
                        var id = (System.Nullable<System.Guid>)value;
                        if (id == null) { continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
        }
    }
}
#pragma warning restore CS1591