#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{


    [System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ktr_tag_module")]
	public partial class KTR_Tag_Module : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the ktr_tag_module entity
		/// </summary>
		public partial class Fields
		{
			public const string KT_ModuleId = "kt_moduleid";
			public const string KTR_Tag_Module_Module = "ktr_Tag_Module_Module";
			public const string KTR_Tag_ModuleId = "ktr_tag_moduleid";
			public const string Id = "ktr_tag_moduleid";
			public const string KTR_TagId = "ktr_tagid";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public KTR_Tag_Module(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public KTR_Tag_Module(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public KTR_Tag_Module(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public KTR_Tag_Module() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "ktr_tag_moduleid";
		
		public const string EntitySchemaName = "ktr_Tag_Module";
		
		public const string EntityLogicalName = "ktr_tag_module";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "ktr_tag_moduleset";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("kt_moduleid")]
		public System.Nullable<System.Guid> KT_ModuleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("kt_moduleid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_tag_moduleid")]
		public System.Nullable<System.Guid> KTR_Tag_ModuleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ktr_tag_moduleid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_tag_moduleid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ktr_tagid")]
		public System.Nullable<System.Guid> KTR_TagId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ktr_tagid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N ktr_Tag_Module_Module
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ktr_Tag_Module_Module")]
		public System.Collections.Generic.IEnumerable<Kantar.StudyDesignerLite.Plugins.KT_Module> KTR_Tag_Module_Module
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KT_Module>("ktr_Tag_Module_Module", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<Kantar.StudyDesignerLite.Plugins.KT_Module>("ktr_Tag_Module_Module", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public KTR_Tag_Module(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ktr_tag_moduleid"] = base.Id;
                        break;
                    case "ktr_tag_moduleid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
