import { ManagedList } from '../selectors/ManagedListSelectors.json'
import { WebHelper } from '../utils/WebHelper';
import { waitUntilAppIdle } from '../utils/Login';
import { expect, Page } from '@playwright/test';
import { QuestionBank } from '../selectors/QuestionBankSelectors.json';
import { Common } from '../selectors/CommonSelector.json';
import { TestData } from '../Test Data/ManagedListData.json';
import { QuestionBankservice } from './QuestionBankService';
import { Questionnaire } from '../selectors/QuestionnaireSelector.json';


export class ManagedListService {
    protected page: Page;
    private webHelper: WebHelper;

    constructor(page: Page) {
        this.page = page;
        this.webHelper = new WebHelper(this.page);
    }

    async create(ManageListName: string): Promise<void> {
        try {
            await this.webHelper.clickOnTab(ManagedList.Tabs.ManagedList);
            await this.webHelper.clickByAriaLabel(ManagedList.AriaLabel.NewManagedList);

            await this.webHelper.enterTextByRoleTextbox(ManagedList.AriaLabel.ManageListNameTextBox, ManageListName);

            await this.webHelper.saveAndCloseQuickCreateRecord();

        } catch (e) {
            console.log(`Error while creating Managelist: ${(e as Error).message}`);
            throw e;
        }
    }
    async selectManagedListTab(): Promise<void> {
        try {
            await this.webHelper.clickOnTab(ManagedList.Tabs.ManagedList);
        } catch (e) {
            console.log(`Error while click on Managelist: ${(e as Error).message}`);
            throw e;
        }
    }

    async addQuestion(manageListName: string, questionName: string, isVisible: boolean = true): Promise<void> {
        try {
            await this.webHelper.clickonButtonByLabel(manageListName);
            await this.webHelper.clickByAriaLabel(ManagedList.AriaLabel.NewQuestionAddButton);
            await this.webHelper.clickByAriaLabel(ManagedList.AriaLabel.SearchQLSearchIcon);
            await this.webHelper.clickByAriaLabel(ManagedList.AriaLabel.SearchMLQuestionList);
            await this.webHelper.saveAndCloseQuickCreateRecord();
            if (isVisible)
                await this.validateAndVerifySave();
            console.log(`Question added to Managed List successfully`);

        } catch (e) {
            console.log(`Error while adding question to ML : ${(e as Error).message}`);
            throw e;
        }
    }
    async selectTheManagedList(manageListName: string): Promise<void> {
        try {
            await this.webHelper.verifyLinkText(manageListName);
            await this.webHelper.clickonLinkText(manageListName);

        } catch (e) {
            console.log(`Error while select the Managed List : ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyAddedManagedListDetails(manageListName: string, IsAutoGenerated: string, isVisible: boolean = true): Promise<void> {
        try {
            if (isVisible) {
                await this.webHelper.verifyLinkText(manageListName);
                await this.webHelper.validateLockedField(IsAutoGenerated);
            }
            else {
                await this.webHelper.verifyLinkText(manageListName, isVisible);
                await this.webHelper.validateLockedField(IsAutoGenerated, isVisible);
            }
        } catch (e) {
            console.log(`Error while verifying the Managed List name and Autogenerated Type : ${(e as Error).message}`);
            throw e;
        }
    }
    async clickOnManagedList(manageListName: string): Promise<void> {
        try {
            await this.webHelper.clickonLinkText(manageListName);
            await this.webHelper.saveRecord();
            await this.webHelper.saveRecord();
        } catch (e) {
            console.log(`Error while click on the Managed List name : ${(e as Error).message}`);
            throw e;
        }
    }

    async editQuestionLocationFromML(questionName: string, location: string): Promise<void> {
        try {
            await this.webHelper.doubleClickOnLabel(questionName);
            await this.webHelper.verifySaveButton();
            await this.webHelper.selectOptionSet(ManagedList.AriaLabel.Location, location)
            await this.webHelper.saveRecord();
            await this.webHelper.saveAndCloseRecord();
            await this.webHelper.verifyTheLabelValue(location);

        } catch (e) {
            console.log(`Error while editing the Question Location from ML : ${(e as Error).message}`);
            throw e;
        }
    }
    async editManagedListLocationFromQL(managedListName: string, location: string): Promise<void> {
        try {
            await this.webHelper.clickOnTab(ManagedList.Tabs.ManagedList)
            await this.webHelper.clickOnGridCellText(managedListName)
            await this.webHelper.selectOptionSet(ManagedList.AriaLabel.Location, location)
            await this.webHelper.saveAndCloseRecord();
            await this.webHelper.verifyGridCellText(location)
            await this.webHelper.saveAndCloseRecord();

        }
        catch (e) {
            console.log(`Error while editing the Question Location from QL : ${(e as Error).message}`);
        }
    }

    async verifyAddedQuestionDetails(questionName: string, location: string, projectName: string): Promise<void> {
        try {
            await this.webHelper.verifySaveButton();
            await this.webHelper.saveRecord();
            await this.webHelper.verifyTheLabelValue(questionName);
            await this.webHelper.verifyTheLabelValue(location);
            await this.webHelper.verifyTheSpantext(projectName);

        } catch (e) {
            console.log(`Error while verifying the Question Details in Managed List : ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyMLNameTextFieldIsEditable(isEditable: boolean = true): Promise<void> {
        try {
            await this.webHelper.verifySaveButton();
            if (isEditable) {
                await this.webHelper.VerifyInputFieldIsEditable(ManagedList.AriaLabel.Name, isEditable);
                console.log("Managed List Name Text field is Editable")
            }
            else {
                await this.webHelper.VerifyInputFieldIsEditable(ManagedList.AriaLabel.Name);
                console.log("Managed List Name Text field is Non-Editable/Readonly")
            }

        } catch (e) {
            console.log(`Error while verifying  Managed List Name Text field is editable or not : ${(e as Error).message}`);
            throw e;
        }
    }
    async clickonSaveRecord(): Promise<void> {
        try {
            await this.webHelper.verifySaveButton();
            await this.page.waitForTimeout(2000);
            await this.webHelper.saveRecord();
            await this.page.waitForTimeout(2000);
            await this.webHelper.saveRecord();
            console.log(`Clicked on Save button`);
        } catch (e) {
            console.log(`Error while click on Save button : ${(e as Error).message}`);
            throw e;
        }
    }

    async getManagedListNames(): Promise<string[]> {
        const managedList = ManagedList.CSS.ManagedListName;
        try {
            await this.webHelper.verifySaveButton();
            await this.page.waitForTimeout(2000);
            await this.page.locator(managedList).allInnerTexts();

            var managedListNames: string[] = [];
            const list = this.page.locator(managedList);
            const managedListName = this.page.locator(managedList);
            const listcount = await list.count();
            for (let index = 0; index < listcount; index++) {
                const text = await managedListName.nth(index).textContent();
                if (text) {
                    managedListNames.push(text.trim());
                }
            }
            return managedListNames;
        } catch (e) {
            console.log(`Error while get the Managed List names : ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyDragAndDropElements(name1: string, name2: string): Promise<void> {
        try {
            await this.page.waitForLoadState("load");
            var managedList: string[] = await this.getManagedListNames();
            await expect(managedList[0]).toBe(name2);
            await expect(managedList[1]).toBe(name1);

        } catch (e) {
            console.log(`Error while validating the Managed List names after drag and drop : ${(e as Error).message}`);
            throw e;
        }
    }

    async validatebutton(buttonName: string, isVisible: boolean = true): Promise<void> {
        try {
            await this.webHelper.verifyTheSpantext(buttonName, isVisible);

        } catch (e) {
            console.log(`Error while validating the button ${buttonName}: ${(e as Error).message}`);
            throw e;
        }
    }
    async clickOnNewManagedListEntityButton(): Promise<void> {
        try {
            await this.webHelper.clickOnCommandBarBtn(ManagedList.AriaLabel.NewManagedListEntity);
        } catch (e) {
            console.log(`Error while click on the Managed List Entity button : ${(e as Error).message}`);
            throw e;
        }
    }

    async fillAnswerText(answerText: string): Promise<void> {
        try {
            await this.page.waitForTimeout(3000);
            await this.webHelper.enterTextByRoleTextbox(ManagedList.AriaLabel.AnswerText, answerText);
        } catch (e) {
            console.log(`Error while Entering the Answer Text : ${(e as Error).message}`);
            throw e;
        }
    }
    async clickOnSaveandCreateNewbutton(): Promise<void> {
        try {
            await this.webHelper.clickOnButton(ManagedList.AriaLabel.SaveAndCloseOptions);
            await this.webHelper.clickOnCommandBarBtn(ManagedList.AriaLabel.SaveCreateNew);
        } catch (e) {
            console.log(`Error while click on the Managed List Entity button : ${(e as Error).message}`);
            throw e;
        }
    }

    async switchToManagedListEntityDropdown(btnName: string, text: string): Promise<void> {
        try {
            await this.webHelper.clickOnButton(btnName);
            await this.webHelper.clickonStartWithText(text)
        } catch (e) {
            console.log(`Error while Switch into Managed List Entity: ${(e as Error).message}`);
            throw e;
        }
    }

    async verifyQuickCreateWindow(): Promise<void> {
        try {
            await this.webHelper.verifyText(ManagedList.Text.QuickCreate);
        } catch (e) {
            console.log(`Error while verifying the Quick Create: Managed List Entity window : ${(e as Error).message}`);
            throw e;
        }
    }

    async verifyManagedListAutoPopulated(managedList: string): Promise<void> {
        try {
            await this.webHelper.verifyLinkText(managedList);
        } catch (e) {
            console.log(`Error while validating ML field is automatically populated : ${(e as Error).message}`);
            throw e;
        }
    }


    async verifyQuickCreateWindowFieldsAreEmpty(): Promise<void> {
        try {
            await this.page.waitForTimeout(3000);
            const text = await this.webHelper.getTextValue(ManagedList.AriaLabel.AnswerText);
            const code = await this.webHelper.getTextValue(ManagedList.AriaLabel.AnswerCode);
            await expect(text).toBe("");
            await expect(code).toBe("");

        } catch (e) {
            console.log(`Error while verifying Fields values in the Quick Create: Managed List Entity window : ${(e as Error).message}`);
            throw e;
        }
    }
    async getAllAnswerTextsInManagedListEntity(): Promise<string[]> {
        var answerTexts: string[];
        try {
            await this.page.waitForTimeout(2000);
            answerTexts = await this.webHelper.getAllAnswerTexts(QuestionBank.CSS.AnswerText);
            return answerTexts;
        } catch (e) {
            console.log(`Error while  getting the Answer Text values in Managed List Entity: ${(e as Error).message}`);
            throw e;
        }
    }


    async verifyAddedManagedListLinkInQuestionnaire(manageListName: string): Promise<void> {
        try {
            await this.webHelper.verifyLinkText(manageListName);
        } catch (e) {
            console.log(`Error while verifying the Managed List name : ${(e as Error).message}`);
            throw e;
        }
    }



    async getManagedListQuestionNames(): Promise<string[]> {
        const questions = Common.CSS.Rows;
        try {
            await this.webHelper.verifySaveButton();
            await this.page.waitForTimeout(2000);
            await this.page.locator(questions).allInnerTexts();

            var questionListNames: string[] = [];
            const list = this.page.locator(questions);
            const questionListName = this.page.locator(questions);
            const listcount = await list.count();
            for (let index = 0; index < listcount; index++) {
                const text = await questionListName.nth(index).textContent();
                if (text) {
                    questionListNames.push(text.trim());
                }
            }
            return questionListNames;
        } catch (e) {
            console.log(`Error while get the Managed List names : ${(e as Error).message}`);
            throw e;
        }
    }

    async deleteQuestionsInManagedList(questionName: string): Promise<void> {

        try {
            await this.webHelper.deleteAllSubgridRecords(ManagedList.AriaLabel.DeleteQuestionnaireLineManagedList);
            await this.page.waitForTimeout(2000);
            await this.webHelper.clickOnConfirmationPopup(Common.Text.Delete);

        } catch (e) {
            console.log(`Error while deleting the question in Managed List : ${(e as Error).message}`);
            throw e;
        }
    }
    async VerifyErrorMessage(): Promise<void> {
        const errorMessage = TestData.DeleteErrorMessage;
        try {
            await this.webHelper.verifyTheSpantext(errorMessage);
        } catch (e) {
            console.log(`Error while validating the Error Message for Deleting the Managed List Entity: ${(e as Error).message}`);
            throw e;
        }
    }
    async deleteTheAnswer(): Promise<void> {
        try {
            await this.webHelper.clickOnCommandBarBtn(Common.Text.Delete);
            await this.page.waitForTimeout(2000);
            await this.webHelper.clickOnButton(Common.Text.Delete);
        } catch (e) {
            console.log(`Error while  Deleting the Managed List Entity: ${(e as Error).message}`);
            throw e;
        }
    }

    async validateAICodeForAnswerText(): Promise<string> {
        const key = Questionnaire.CSS.AnswerCode;
        try {
            await this.webHelper.verifySaveButton();
            await this.webHelper.saveRecord();
            await this.page.waitForTimeout(7000);
            await this.webHelper.saveRecord();
            await this.page.reload();
            await this.webHelper.verifySaveButton();
            await this.webHelper.saveRecord();
            await this.page.reload();
            await this.webHelper.verifySaveButton();
            await this.webHelper.clickOnTab(ManagedList.Tabs.Entities);
            await this.webHelper.saveRecord();
            const answerCode: string[] = await this.webHelper.getAutomationKeyGridCellValue(key);
            return answerCode[0];


        } catch (e) {
            console.log(`Error while validating the AI Answer Code : ${(e as Error).message}`);
            throw e;
        }
    }
    async toggleAnswerCodeEditable(): Promise<void> {
        try {

            await this.webHelper.verifySwitchbutton(ManagedList.AriaLabel.AnswerCodeEditable_No);
            await this.webHelper.clickOnSwitchbutton(ManagedList.AriaLabel.AnswerCodeEditable_No);
            await this.webHelper.saveRecord();
        } catch (e) {
            console.log(`Error while  toggle the Answer Code Editable: ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyAnswerTextIsEditableMandatory(): Promise<void> {
        try {
            await this.webHelper.validateRequiredField(ManagedList.AriaLabel.AnswerText);
            await this.webHelper.validateEditableField(ManagedList.AriaLabel.AnswerText);
        } catch (e) {
            console.log(`Error while validating the Answer Text field is Editable and mandatory : ${(e as Error).message}`);
            throw e;
        }
    }
    async deleteManagedList(): Promise<void> {
        try {
            await this.webHelper.clickOnCommandBarBtn(Common.Text.Delete);
            await this.webHelper.verifyText(Common.Text.ConfirmDeletion);
            await this.webHelper.clickOnButton(Common.Text.Delete);
        } catch (e) {
            console.log(`Error while  Deleting the Managed List: ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyConfirmDeletionPopup(): Promise<void> {
        try {
            await this.webHelper.clickOnCommandBarBtn(Common.Text.Delete);
            await this.webHelper.verifyText(Common.Text.ConfirmDeletion);
            await this.webHelper.verifyButtonText(Common.Text.Delete);
            await this.webHelper.verifyButtonText(Common.Text.QCCancel);

        } catch (e) {
            console.log(`Error while  verifying the Confirm Deletion Popup message in the Managed List: ${(e as Error).message}`);
            throw e;
        }
    }
    async filterEntities(entity: string): Promise<void> {
        try {
            await this.webHelper.searchRecord(ManagedList.Placeholder.SearchMLEntities, entity);
        } catch (e) {
            console.log(`Error while filtering the record in the Managed List Entiies Searchbox: ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyEntity(entity: string, isVisible: boolean = true): Promise<void> {
        try {
            if (isVisible)
                await this.webHelper.verifyText(entity);
            else
                await this.webHelper.verifyText(entity, isVisible)
        } catch (e) {
            console.log(`Error while validating the Entity after filtering: ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyTheTab(tab: string): Promise<void> {
        try {
            await this.webHelper.verifyTheTab(tab);
        } catch (e) {
            console.log(`Error while validating the tab ${tab}: ${(e as Error).message}`);
            throw e;
        }
    }
    async verifyTheManagedList(manageListName: string, isVisible: boolean = true): Promise<void> {
        try {
            if (isVisible)
                await this.webHelper.verifyText(manageListName);
            else
                await this.webHelper.verifyText(manageListName, isVisible);

        } catch (e) {
            console.log(`Error while verifying the Managed List Name : ${(e as Error).message}`);
            throw e;
        }
    }
    async getEntitiesCountInStudyAllocation(): Promise<number> {
        const locator = ManagedList.CSS.StudyAllocationEntites
        try {
            await this.validateAndVerifySave();
            await this.clickonSaveRecord();
            await this.webHelper.clickOnTab(ManagedList.Tabs.StudyAllocation);
            return await this.webHelper.getCountOfColumns(locator);

        } catch (e) {
            console.log(`Error while getting the count in Entities in Study Allocation: ${(e as Error).message}`);
            throw e;
        }
    }

    async selectCheckboxForEntityInStudyAllocation(entity: string): Promise<void> {
        const label = "Select " + entity + " for bulk operations on Draft studies";
        const btnName = ManagedList.Button.SaveChanges
        try {
            await this.webHelper.selectcheckbox(label);
            await this.webHelper.clickOnButton(btnName);

        } catch (e) {
            console.log(`Error while select and saving the Entity in Study Allocation: ${(e as Error).message}`);
            throw e;
        }
    }
    async getAnswerCode(): Promise<string> {
        const key = Questionnaire.CSS.AnswerCode;
        try {
            const answerCode: string[] = await this.webHelper.getAutomationKeyGridCellValue(key);
            return answerCode[0];

        } catch (e) {
            console.log(`Error while getting the Answer Code : ${(e as Error).message}`);
            throw e;
        }
    }
    async validateAndVerifySave(): Promise<void> {
        try {
            await this.webHelper.verifyTheSpantext(ManagedList.Text.Saved)
            await this.page.reload();
            await this.webHelper.verifyTheSpantext(ManagedList.Text.Saved)
            await this.webHelper.verifyNewButton();
            await this.webHelper.verifySaveButton();
            console.log(`verified the Save button in Menu bar`);
        } catch (e) {
            console.log(`Error while verifying the Save button : ${(e as Error).message}`);
            throw e;
        }
    }
    async deactivateManagedListEntity(): Promise<void> {
        try {
            await this.webHelper.clickOnCommandBarBtn(Common.Text.Deactivate);
            await this.webHelper.clickOnConfirmationPopup(Common.Text.Deactivate);
        } catch (e) {
            console.log(`Error while deactivating the ML Entity ${(e as Error).message}`);
            throw e;
        }
    }
    async openMLEntity(MLEntity: string): Promise<void> {
        try {

            await this.webHelper.clickOnButton(MLEntity);

        } catch (e) {
            console.log(`Error while opening the Managed List Entity : ${(e as Error).message}`);
            throw e;
        }
    }

    async verifyDeleteButtonFromMLContextMenu(): Promise<void> {
        try {
            await this.webHelper.validateCommandBarBtnNotVisible(ManagedList.AriaLabel.DeleteQuestionnaireLineManagedList, ManagedList.AriaLabel.MoreCommandsForManagedList);
            await this.page.click('body');
        } catch (e) {
            console.log(`Error while verifying the Delete Button in Context Menu: ${(e as Error).message}`);
            throw e;
        }
    }

    async selectTheManagedListInGrid(managedListName: string): Promise<void> {
        try {
            await this.webHelper.selectGridCellText(managedListName);
        } catch (e) {
            console.log(`Error while select the Managed List in grid : ${(e as Error).message}`);
            throw e;
        }
    }
    async updateTheMLName(mlName: string): Promise<void> {
        try {
            await this.webHelper.verifySaveButton();
            await this.webHelper.clickByAriaLabel(ManagedList.AriaLabel.Name);
            await this.webHelper.enterTextByRoleTextbox(ManagedList.AriaLabel.Name, mlName);
            await this.webHelper.saveAndCloseRecord();
        } catch (e) {
            console.log(`Error while updating the  Managed List Name : ${(e as Error).message}`);
            throw e;
        }
    }

    async clickOnAnswerText(Text: string): Promise<void> {
        const answerText = QuestionBank.CSS.AnswerText;
        try {
            await this.page.locator(answerText).filter({ hasText: `${Text}` }).waitFor();
            await this.page.locator(answerText).filter({ hasText: `${Text}` }).click();

        } catch (e) {
            console.log(`Error while click on the Answer Text: ${(e as Error).message}`);
            throw e;
        }
    }
    async selectAnswerTextByLabel(Text: string): Promise<void> {
        try {
            await this.webHelper.verifySaveButton();
            await this.webHelper.doubleClickOnLabel(Text);

        } catch (e) {
            console.log(`Error while select the Answer Text: ${(e as Error).message}`);
            throw e;
        }
    }

}