import { expect, mergeTests } from '@playwright/test';
import { logintest } from '../Fixture/LoginFixture';
import { createproject } from '../Fixture/CreateProjectWithStdQue';
import { LoginToMDAWithTestUser, waitUntilAppIdle } from '../../utils/Login';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { Utils } from "../../utils/utils";
import { DropDownList } from '../../constants/DropDownList.json';
import { WebHelper } from '../../utils/WebHelper';
import { CommonTestData } from '../../Test Data/CommonTestData.json';
import { Questionnaire } from '../../selectors/QuestionnaireSelector.json';
import { Common } from '../../selectors/CommonSelector.json';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { ProjectService } from '../../services/ProjectService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';
import { ManagedListService } from '../../services/ManagedListService';

// Using a LoginFixture and CreateProjectWithStdQue to handle setup and teardown for all test cases:
// 1. Login the application with CS user
// 2. Create the project and add a question before each test execution.
// 3. Delete the project after the each test case execution

let managedListName: any;
let webHelper: WebHelper;
let questionnaireService: Questionnaireservice;
let projectService: ProjectService;
let managedListService: ManagedListService;

// Merges the results of the login test and the create a Project test into a single combined test execution.
const test = mergeTests(logintest, createproject);

//  Executes setup steps before each test case to prepare the required environment.
test.beforeEach(async ({ page, loginPage, guid, projectName }) => {
    webHelper = new WebHelper(page);
    questionnaireService = new Questionnaireservice(page);
    projectService = new ProjectService(page);
    managedListService = new ManagedListService(page);

    managedListName = MLTestData.ManagedListName + Utils.generateText();


    await test.step('Create and verify the Manage list from Project', async () => {
        await managedListService.create(managedListName);
        await managedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_No);
    });
});

test("[2530092] Verify that through Edit must applying shared list placeholders - Managed Lists tab", { tag: ['@Regression', '@ManagedList'] }, async ({ page, browser }) => {
    test.info().annotations.push({ type: 'TestCaseId', description: '2530092' });

    await test.step('Now go to Manage list tab from Master questionnaire line', async () => {
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await questionnaireService.clickonEditbutton();
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);
    });

    await test.step('Apply the created Managed list placeholder from Managed list tab', async () => {
        await questionnaireService.addManageListInQuestionnaire(managedListName);
    });

    await test.step('Manage list added in the Questionnaire Line should be visible in the respective Manage List tab', async () => {
        var managedList: string[] = await managedListService.getManagedListNames();
        await webHelper.saveAndCloseRecord();
        await webHelper.verifySaveButton();
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await questionnaireService.clickonEditbutton();
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);
        await webHelper.clickOnGridCellText(managedListName);
        await expect(managedList[0]).toBe(managedListName);
    });
});


test("[2595050] Verify when a question is deleted from the ML then the link displayed in the Questionnaire is also removed", { tag: ['@Regression', '@Questionnaire'] }, async ({ page, browser }) => {
    test.info().annotations.push({ type: 'TestCaseId', description: '2595050' });
    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();

    await test.step('Add question to Manage list', async () => {
        await managedListService.addQuestion(managedListName, questionName);
        await webHelper.saveAndCloseRecord();
    });

    await test.step('Verify wether the hyper link is displayed in the Questionnaire', async () => {
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await managedListService.verifyAddedManagedListLinkInQuestionnaire(managedListName);
    });

    await test.step('Navigate to the Managed List tab', async () => {
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);
        await managedListService.clickOnManagedList(managedListName);
    });

    await test.step('Delete the question from the Managed list', async () => {
        await webHelper.verifySaveButton();
        await managedListService.deleteQuestionsInManagedList(questionName);

    });

    await test.step('Verify the question link is removed from the Questionnaire Line Managed list tab', async () => {
        await webHelper.saveAndCloseRecord();
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await questionnaireService.clickonEditbutton();
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);

        var questionList: string[] = await managedListService.getManagedListQuestionNames();
        await expect(questionList.length).toBe(0);
    });
});

test("[2539091] To check if info icon is available for Scripter user on every questions added to the Questionnaireline in QL tab", { tag: ['@Regression', '@Questionnaire'] }, async ({ page, browser ,projectName}) => {
     test.info().annotations.push({ type: 'TestCaseId', description: '2539091' });
    const questionnaireService = new Questionnaireservice(page);
    const projectService = new ProjectService(page);

    const webHelper = new WebHelper(page);

    await test.step('Deactivate the Question from Questionnaire', async () => {
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await webHelper.clickonStartWithText("Edit");
        await projectService.clickonButton(Common.Text.Deactivate);
        await webHelper.verifyCommandBarBtn(Common.Text.Activate);
        await page.goBack();
        await webHelper.verifySaveButton();
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
    });
    await test.step('verify the Deactived Question In Active Questions', async () => {
        await webHelper.verifyTheSpantext(TestData.StandardQuestion, false);
        await webHelper.verifyTheLabeltext(DropDownList.QuestionBank.SmallTextInput, false);
        await webHelper.verifyTheSpantext(TestData.StandardQuest_VariableName, false);
    });

    await test.step('Now share a project to scripter user from User management', async () => {
        await projectService.addScripterUserToProject();
        await webHelper.saveRecord();
        await page.close();
    });

    const context = await browser.newContext();
    const scripterUserPage = await context.newPage();
    const webHelperSecond = new WebHelper(scripterUserPage);
    const newProjectService = new ProjectService(scripterUserPage);
    const scripterUserQuestionnaireService = new Questionnaireservice(scripterUserPage);
    await test.step('Login as a scripter user', async () => {
        await LoginToMDAWithTestUser(scripterUserPage, TestUser.ScripterUser, AppId.UC1, AppName.UC1, true);
    });
    await test.step('Go to project > search for the shared project', async () => {
        await newProjectService.searchForProject(projectName);
    });

    await test.step('Add a Question to the Project', async () => {
        await scripterUserQuestionnaireService.addQuestion(CommonTestData.StandardDummyQuestion, CommonTestData.QuestionTitle, false);
        await scripterUserQuestionnaireService.validateQuestionsAddedInQuestionnaire(CommonTestData.StandardDummyQuestion, DropDownList.QuestionBank.MultiChoice, CommonTestData.StandardDummyQuestionText);
    });
    await test.step('Now check if there exists an info icon', async () => {
        await scripterUserQuestionnaireService.verifyAndHovertheInfoIcon(CommonTestData.StandardDummyQuestion);
    });
    await test.step('Check if info tool tip contain certain details', async () => {
        await scripterUserQuestionnaireService.validatingToolTipText(CommonTestData.StandardDummyQuestion);
    });

    await test.step('Change to InActive Questions', async () => {
        await webHelperSecond.selectByOption(Common.CSS.ActiveQuestions, TestData.InactiveQuestions);
    });

    await test.step('Verify the Question Details in Inactive Questions and check question is strike out', async () => {
        await scripterUserQuestionnaireService.verifyQuestionsStrikeout(TestData.StandardQuestionText2);
    });
});

