// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Features.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Api.Features.CommissioningMarkets.CommissioningMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("CommissioningMarkets");
                });

            modelBuilder.Entity("Api.Features.ConfigurationQuestions.ConfigurationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationQuestionId");

                    b.ToTable("ConfigurationAnswers");
                });

            modelBuilder.Entity("Api.Features.ConfigurationQuestions.ConfigurationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiPrompt")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationQuestions");
                });

            modelBuilder.Entity("Api.Features.ConfigurationQuestions.DependencyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConfigurationQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuestionBank")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TriggeringAnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationQuestionId");

                    b.HasIndex("TriggeringAnswerId");

                    b.ToTable("DependencyRules");
                });

            modelBuilder.Entity("Api.Features.FieldworkMarkets.FieldworkMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("FieldworkMarkets");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.ManagedList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ManagedLists");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.ManagedListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Value");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ManagedListId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ManagedListItems_ManagedListId_Value");

                    b.ToTable("ManagedListItems");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.QuestionManagedList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagedListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionnaireLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListId");

                    b.HasIndex("QuestionnaireLineId", "ManagedListId")
                        .IsUnique();

                    b.ToTable("QuestionManagedLists");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.QuestionSubsetLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagedListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionnaireLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubsetDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListId");

                    b.HasIndex("SubsetDefinitionId");

                    b.HasIndex("QuestionnaireLineId", "ManagedListId")
                        .IsUnique();

                    b.ToTable("QuestionSubsetLinks");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.SubsetDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagedListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListId");

                    b.HasIndex("ProjectId", "ManagedListId");

                    b.HasIndex("ProjectId", "ManagedListId", "SignatureHash")
                        .IsUnique();

                    b.ToTable("SubsetDefinitions");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.SubsetMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagedListItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubsetDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListItemId");

                    b.HasIndex("SubsetDefinitionId", "ManagedListItemId")
                        .IsUnique();

                    b.ToTable("SubsetMemberships");
                });

            modelBuilder.Entity("Api.Features.MetricGroups.MetricGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MetricGroups");
                });

            modelBuilder.Entity("Api.Features.Modules.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentModuleId");

                    b.HasIndex("VariableName")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Api.Features.Modules.ModuleQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.HasIndex("ModuleId", "QuestionBankItemId")
                        .IsUnique();

                    b.ToTable("ModuleQuestions");
                });

            modelBuilder.Entity("Api.Features.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Api.Features.Products.ProductConfigQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationQuestionId");

                    b.HasIndex("ProductId", "ConfigurationQuestionId")
                        .IsUnique();

                    b.ToTable("ProductConfigQuestions");
                });

            modelBuilder.Entity("Api.Features.Products.ProductConfigQuestionDisplayRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductConfigQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TriggeringAnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TriggeringConfigurationQuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductConfigQuestionId");

                    b.HasIndex("TriggeringAnswerId");

                    b.HasIndex("TriggeringConfigurationQuestionId");

                    b.ToTable("ProductConfigQuestionDisplayRules");
                });

            modelBuilder.Entity("Api.Features.Products.ProductTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("ProductTemplates");
                });

            modelBuilder.Entity("Api.Features.Products.ProductTemplateLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludeByDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ProductTemplateId");

                    b.HasIndex("QuestionBankItemId");

                    b.ToTable("ProductTemplateLines");
                });

            modelBuilder.Entity("Api.Features.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommissioningMarketId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CostManagementEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("HasStudies")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastStudyModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Methodology")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudyCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommissioningMarketId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ClientId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Api.Features.QuestionBank.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AnswerLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomProperty")
                        .HasColumnType("text");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Facets")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Api.Features.QuestionBank.QuestionBankItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnswerMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AnswerMin")
                        .HasColumnType("integer");

                    b.Property<int?>("AnswerRestrictionMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AnswerRestrictionMin")
                        .HasColumnType("integer");

                    b.Property<string>("AnswerTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ColumnSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomNotes")
                        .HasColumnType("text");

                    b.Property<string>("DataQualityTag")
                        .HasColumnType("text");

                    b.Property<string>("DisplayType")
                        .HasColumnType("text");

                    b.Property<string>("InstructionText")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnswerRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDummy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuestionActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuestionOutOfUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTranslatable")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagedListReferences")
                        .HasColumnType("text");

                    b.Property<string>("Methodology")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MetricGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionFacet")
                        .HasColumnType("text");

                    b.Property<string>("QuestionFormatDetails")
                        .HasColumnType("text");

                    b.Property<string>("QuestionRationale")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("QuestionTitle")
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RestrictedToClient")
                        .HasColumnType("text");

                    b.Property<string>("RestrictionDataType")
                        .HasColumnType("text");

                    b.Property<int?>("RowSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ScalePoint")
                        .HasColumnType("text");

                    b.Property<string>("ScaleType")
                        .HasColumnType("text");

                    b.Property<string>("ScraperNotes")
                        .HasColumnType("text");

                    b.Property<string>("SingleOrMulticode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TableTitle")
                        .HasColumnType("text");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricGroupId");

                    b.HasIndex("ParentQuestionId");

                    b.HasIndex("QuestionText");

                    b.HasIndex("QuestionTitle");

                    b.HasIndex("VariableName", "Version")
                        .IsUnique();

                    b.ToTable("QuestionBankItems");
                });

            modelBuilder.Entity("Api.Features.QuestionnaireLines.QuestionnaireLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnswerMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AnswerMin")
                        .HasColumnType("integer");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<int?>("ColumnSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsDummy")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionFormatDetails")
                        .HasColumnType("text");

                    b.Property<string>("QuestionRationale")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("QuestionTitle")
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text");

                    b.Property<int?>("RowSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ScraperNotes")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.HasIndex("ProjectId", "QuestionBankItemId")
                        .IsUnique()
                        .HasFilter("\"QuestionBankItemId\" IS NOT NULL");

                    b.ToTable("QuestionnaireLines", (string)null);
                });

            modelBuilder.Entity("Api.Features.Studies.FieldworkLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FieldworkMarketId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FieldworkMarketId");

                    b.HasIndex("StudyId", "FieldworkMarketId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("FieldworkLanguages");
                });

            modelBuilder.Entity("Api.Features.Studies.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FieldworkMarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaconomyJobNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MasterStudyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentStudyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectOperationsUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScripterNotes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldworkMarketId");

                    b.HasIndex("MasterStudyId");

                    b.HasIndex("ParentStudyId");

                    b.HasIndex("ProjectId", "MasterStudyId", "Version")
                        .IsUnique();

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyManagedListAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagedListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyQuestionnaireLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListId");

                    b.HasIndex("StudyId");

                    b.HasIndex("StudyQuestionnaireLineId", "ManagedListId")
                        .IsUnique();

                    b.ToTable("StudyManagedListAssignments");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyQuestionSubsetLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagedListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudyQuestionnaireLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubsetDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagedListId");

                    b.HasIndex("StudyId");

                    b.HasIndex("SubsetDefinitionId");

                    b.HasIndex("StudyQuestionnaireLineId", "ManagedListId")
                        .IsUnique();

                    b.ToTable("StudyQuestionSubsetLinks");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyQuestionnaireLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnswerMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AnswerMin")
                        .HasColumnType("integer");

                    b.Property<string>("Classification")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ColumnSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EditCustomAnswerCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDummy")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockAnswerCode")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionFormatDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("QuestionRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("QuestionText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("QuestionTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RowSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ScraperNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.HasIndex("StudyId", "SortOrder")
                        .IsUnique();

                    b.ToTable("StudyQuestionnaireLines");
                });

            modelBuilder.Entity("Api.Features.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Api.Features.ConfigurationQuestions.ConfigurationAnswer", b =>
                {
                    b.HasOne("Api.Features.ConfigurationQuestions.ConfigurationQuestion", "ConfigurationQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("ConfigurationQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationQuestion");
                });

            modelBuilder.Entity("Api.Features.ConfigurationQuestions.DependencyRule", b =>
                {
                    b.HasOne("Api.Features.ConfigurationQuestions.ConfigurationQuestion", "ConfigurationQuestion")
                        .WithMany()
                        .HasForeignKey("ConfigurationQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Features.ConfigurationQuestions.ConfigurationAnswer", "TriggeringAnswer")
                        .WithMany()
                        .HasForeignKey("TriggeringAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConfigurationQuestion");

                    b.Navigation("TriggeringAnswer");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.ManagedList", b =>
                {
                    b.HasOne("Api.Features.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.ManagedListItem", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedList", "ManagedList")
                        .WithMany("Items")
                        .HasForeignKey("ManagedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedList");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.QuestionManagedList", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedList", "ManagedList")
                        .WithMany("QuestionAssignments")
                        .HasForeignKey("ManagedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.QuestionnaireLines.QuestionnaireLine", "QuestionnaireLine")
                        .WithMany()
                        .HasForeignKey("QuestionnaireLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedList");

                    b.Navigation("QuestionnaireLine");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.QuestionSubsetLink", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedList", "ManagedList")
                        .WithMany()
                        .HasForeignKey("ManagedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.QuestionnaireLines.QuestionnaireLine", "QuestionnaireLine")
                        .WithMany()
                        .HasForeignKey("QuestionnaireLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.ManagedLists.SubsetDefinition", "SubsetDefinition")
                        .WithMany("QuestionLinks")
                        .HasForeignKey("SubsetDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ManagedList");

                    b.Navigation("QuestionnaireLine");

                    b.Navigation("SubsetDefinition");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.SubsetDefinition", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedList", "ManagedList")
                        .WithMany()
                        .HasForeignKey("ManagedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedList");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.SubsetMembership", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedListItem", "ManagedListItem")
                        .WithMany()
                        .HasForeignKey("ManagedListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.ManagedLists.SubsetDefinition", "SubsetDefinition")
                        .WithMany("Memberships")
                        .HasForeignKey("SubsetDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedListItem");

                    b.Navigation("SubsetDefinition");
                });

            modelBuilder.Entity("Api.Features.Modules.Module", b =>
                {
                    b.HasOne("Api.Features.Modules.Module", "ParentModule")
                        .WithMany("ChildModules")
                        .HasForeignKey("ParentModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentModule");
                });

            modelBuilder.Entity("Api.Features.Modules.ModuleQuestion", b =>
                {
                    b.HasOne("Api.Features.Modules.Module", "Module")
                        .WithMany("ModuleQuestions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.QuestionBank.QuestionBankItem", "QuestionBankItem")
                        .WithMany("ModuleQuestions")
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("QuestionBankItem");
                });

            modelBuilder.Entity("Api.Features.Products.ProductConfigQuestion", b =>
                {
                    b.HasOne("Api.Features.ConfigurationQuestions.ConfigurationQuestion", "ConfigurationQuestion")
                        .WithMany()
                        .HasForeignKey("ConfigurationQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Features.Products.Product", "Product")
                        .WithMany("ProductConfigQuestions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationQuestion");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Features.Products.ProductConfigQuestionDisplayRule", b =>
                {
                    b.HasOne("Api.Features.Products.ProductConfigQuestion", "ProductConfigQuestion")
                        .WithMany("DisplayRules")
                        .HasForeignKey("ProductConfigQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.ConfigurationQuestions.ConfigurationAnswer", "TriggeringAnswer")
                        .WithMany()
                        .HasForeignKey("TriggeringAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Features.ConfigurationQuestions.ConfigurationQuestion", "TriggeringConfigurationQuestion")
                        .WithMany()
                        .HasForeignKey("TriggeringConfigurationQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductConfigQuestion");

                    b.Navigation("TriggeringAnswer");

                    b.Navigation("TriggeringConfigurationQuestion");
                });

            modelBuilder.Entity("Api.Features.Products.ProductTemplate", b =>
                {
                    b.HasOne("Api.Features.Products.Product", "Product")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Features.Products.ProductTemplateLine", b =>
                {
                    b.HasOne("Api.Features.Modules.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Features.Products.ProductTemplate", "ProductTemplate")
                        .WithMany("ProductTemplateLines")
                        .HasForeignKey("ProductTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.QuestionBank.QuestionBankItem", "QuestionBankItem")
                        .WithMany()
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");

                    b.Navigation("ProductTemplate");

                    b.Navigation("QuestionBankItem");
                });

            modelBuilder.Entity("Api.Features.Projects.Project", b =>
                {
                    b.HasOne("Api.Features.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Features.CommissioningMarkets.CommissioningMarket", "CommissioningMarket")
                        .WithMany()
                        .HasForeignKey("CommissioningMarketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Features.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("CommissioningMarket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Features.QuestionBank.QuestionAnswer", b =>
                {
                    b.HasOne("Api.Features.QuestionBank.QuestionBankItem", "QuestionBankItem")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionBankItem");
                });

            modelBuilder.Entity("Api.Features.QuestionBank.QuestionBankItem", b =>
                {
                    b.HasOne("Api.Features.MetricGroups.MetricGroup", "MetricGroup")
                        .WithMany()
                        .HasForeignKey("MetricGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Features.QuestionBank.QuestionBankItem", "ParentQuestion")
                        .WithMany()
                        .HasForeignKey("ParentQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MetricGroup");

                    b.Navigation("ParentQuestion");
                });

            modelBuilder.Entity("Api.Features.QuestionnaireLines.QuestionnaireLine", b =>
                {
                    b.HasOne("Api.Features.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.QuestionBank.QuestionBankItem", "QuestionBankItem")
                        .WithMany()
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("QuestionBankItem");
                });

            modelBuilder.Entity("Api.Features.Studies.FieldworkLanguage", b =>
                {
                    b.HasOne("Api.Features.FieldworkMarkets.FieldworkMarket", "FieldworkMarket")
                        .WithMany()
                        .HasForeignKey("FieldworkMarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldworkMarket");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Api.Features.Studies.Study", b =>
                {
                    b.HasOne("Api.Features.FieldworkMarkets.FieldworkMarket", "FieldworkMarket")
                        .WithMany()
                        .HasForeignKey("FieldworkMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.Study", "MasterStudy")
                        .WithMany()
                        .HasForeignKey("MasterStudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.Study", "ParentStudy")
                        .WithMany("ChildVersions")
                        .HasForeignKey("ParentStudyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Features.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldworkMarket");

                    b.Navigation("MasterStudy");

                    b.Navigation("ParentStudy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyManagedListAssignment", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedList", "ManagedList")
                        .WithMany()
                        .HasForeignKey("ManagedListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.StudyQuestionnaireLine", "StudyQuestionnaireLine")
                        .WithMany("ManagedListAssignments")
                        .HasForeignKey("StudyQuestionnaireLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedList");

                    b.Navigation("Study");

                    b.Navigation("StudyQuestionnaireLine");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyQuestionSubsetLink", b =>
                {
                    b.HasOne("Api.Features.ManagedLists.ManagedList", "ManagedList")
                        .WithMany()
                        .HasForeignKey("ManagedListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.Studies.StudyQuestionnaireLine", "StudyQuestionnaireLine")
                        .WithMany("SubsetLinks")
                        .HasForeignKey("StudyQuestionnaireLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Features.ManagedLists.SubsetDefinition", "SubsetDefinition")
                        .WithMany()
                        .HasForeignKey("SubsetDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedList");

                    b.Navigation("Study");

                    b.Navigation("StudyQuestionnaireLine");

                    b.Navigation("SubsetDefinition");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyQuestionnaireLine", b =>
                {
                    b.HasOne("Api.Features.QuestionBank.QuestionBankItem", "QuestionBankItem")
                        .WithMany()
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Features.Studies.Study", "Study")
                        .WithMany("QuestionnaireLines")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionBankItem");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Api.Features.ConfigurationQuestions.ConfigurationQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.ManagedList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("QuestionAssignments");
                });

            modelBuilder.Entity("Api.Features.ManagedLists.SubsetDefinition", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("QuestionLinks");
                });

            modelBuilder.Entity("Api.Features.Modules.Module", b =>
                {
                    b.Navigation("ChildModules");

                    b.Navigation("ModuleQuestions");
                });

            modelBuilder.Entity("Api.Features.Products.Product", b =>
                {
                    b.Navigation("ProductConfigQuestions");

                    b.Navigation("ProductTemplates");
                });

            modelBuilder.Entity("Api.Features.Products.ProductConfigQuestion", b =>
                {
                    b.Navigation("DisplayRules");
                });

            modelBuilder.Entity("Api.Features.Products.ProductTemplate", b =>
                {
                    b.Navigation("ProductTemplateLines");
                });

            modelBuilder.Entity("Api.Features.QuestionBank.QuestionBankItem", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ModuleQuestions");
                });

            modelBuilder.Entity("Api.Features.Studies.Study", b =>
                {
                    b.Navigation("ChildVersions");

                    b.Navigation("QuestionnaireLines");
                });

            modelBuilder.Entity("Api.Features.Studies.StudyQuestionnaireLine", b =>
                {
                    b.Navigation("ManagedListAssignments");

                    b.Navigation("SubsetLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
