#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BotComponentCollectionSharingRoleType
	{
		
		/// <summary>
		/// Can author the component collection
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Component collection author", 2, "#0000ff", "Can author the component collection")]
		ComponentCollectionAuthor = 3,
		
		/// <summary>
		/// Has access to the content of the component collection and can add component collection to the copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Component collection user", 1, "#0000ff", "Has access to the content of the component collection and can add component colle" +
			"ction to the copilot")]
		ComponentCollectionUser = 2,
		
		/// <summary>
		/// Copilot user has access to the content of the component collection
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot user", 0, "#0000ff", "Copilot user has access to the content of the component collection")]
		CopilotUser = 1,
	}
}
#pragma warning restore CS1591
