#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	/// <summary>
	/// Select the records to send the direct email to
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BulkEmail_Recipient
	{
		
		/// <summary>
		/// Send direct email to all the records on all the pages in the current view.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All records on all pages", 2, null, "Send direct email to all the records on all the pages in the current view.")]
		AllRecordsOnAllPages = 3,
		
		/// <summary>
		/// Send direct email to all the records on this page.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All records on current page", 1, null, "Send direct email to all the records on this page.")]
		AllRecordsOnCurrentPage = 2,
		
		/// <summary>
		/// Send direct email only to the records you selected on this page.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Selected records on current page", 0, null, "Send direct email only to the records you selected on this page.")]
		SelectedRecordsOnCurrentPage = 1,
	}
}
#pragma warning restore CS1591
