#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	/// <summary>
	/// Field permission to read unmasked values.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Field_Security_Permission_ReadUnmasked
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All Records", 2)]
		AllRecords = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Allowed", 0)]
		NotAllowed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("One Record", 1)]
		OneRecord = 1,
	}
}
#pragma warning restore CS1591
