#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum FlipSwitch_Options
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Off", 0)]
		Off = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("On", 1)]
		On = 1,
	}
}
#pragma warning restore CS1591
