#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum KT_QuestionType
	{

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Display screen", 8)]
        DisplayScreen = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Large text input", 6)]
        LargeTextInput = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Logic", 3)]
        Logic = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Multiple choice", 1)]
        MultipleChoice = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute(" Multiple-choice matrix", 9)]
        MultipleChoiceMatrix = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Numeric input", 5)]
        NumericInput = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Numeric matrix", 7)]
        NumericMatrix = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Single choice", 2)]
        SingleChoice = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Single-choice matrix", 4)]
        SingleChoiceMatrix = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Small text input", 0)]
        SmallTextInput = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Text input matrix", 10)]
        TextInputMatrix = 13,
    }
}
#pragma warning restore CS1591
