#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{


    [System.Runtime.Serialization.DataContractAttribute()]
    public enum KTR_SortOrder
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Alphabetical", 0, null, "", "", 1033, "Alphabetical")]
        Alphabetical = 847610000,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Normal", 3, null, "", "", 1033, "Normal")]
        Normal = 847610003,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Random", 1, null, "", "", 1033, "Random")]
        Random = 847610001,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Rotated", 4, null, "", "", 1033, "Rotated")]
        Rotated = 847610004,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Shared Random", 2, null, "", "", 1033, "Shared Random")]
        SharedRandom = 847610002,
    }
}
#pragma warning restore CS1591
