#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	/// <summary>
	/// The stage of an approval and a linked approval request.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_Flow_ApprovalStage
	{
		
		/// <summary>
		/// Basic stage (the single stage for Basic approvals).
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basic", 1, "#0000ff", "Basic stage (the single stage for Basic approvals).")]
		Basic = 192350001,
		
		/// <summary>
		/// The approval is complete.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Complete", 2, "#0000ff", "The approval is complete.")]
		Complete = 192351000,
		
		/// <summary>
		/// Not specified.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Specified", 0, "#0000ff", "Not specified.")]
		NotSpecified = 192350000,
	}
}
#pragma warning restore CS1591
