#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Photo_Resolution
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("1024 x 768", 2)]
		_1024X768 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("1600 x 1200", 3)]
		_1600X1200 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("2048 x 1536", 4)]
		_2048X1536 = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("2592 x 1936", 5)]
		_2592X1936 = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("640 x 480", 1)]
		_640X480 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Device Default", 0)]
		DeviceDefault = 0,
	}
}
#pragma warning restore CS1591
