#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	/// <summary>
	/// Choose when the appointment should end
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum RangeEnds_Options
	{
		
		/// <summary>
		/// The appointment series ends by a specied end date
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("By end date", 2, "#0000ff", "The appointment series ends by a specied end date")]
		ByEndDate = 3,
		
		/// <summary>
		/// The appointment series ends after a specified number of occurences
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("By number of occurrences", 1, "#0000ff", "The appointment series ends after a specified number of occurences")]
		ByNumberOfOccurrences = 2,
		
		/// <summary>
		/// The appointment series never ends
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Never", 0, "#0000ff", "The appointment series never ends")]
		Never = 1,
	}
}
#pragma warning restore CS1591
