#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	/// <summary>
	/// Options for how often should an appointment repeat?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum RepeatPattern_Options
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Daily", 0, "#0000ff")]
		Daily = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Monthly", 2, "#0000ff")]
		Monthly = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Weekly", 1, "#0000ff")]
		Weekly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yearly", 3, "#0000ff")]
		Yearly = 3,
	}
}
#pragma warning restore CS1591
