#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kantar.StudyDesignerLite.Plugins
{
	
	
	/// <summary>
	/// Synapse Link entity metadata state
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SynapseLinkEntityMetadataState
	{
		
		/// <summary>
		/// Created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 4, "#0000ff", "Created")]
		Created = 8,
		
		/// <summary>
		/// Failure
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failure", 5, "#0000ff", "Failure")]
		Failure = 16,
		
		/// <summary>
		/// Metadata creating
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MetadataCreating", 2, "#0000ff", "Metadata creating")]
		Metadatacreating = 2,
		
		/// <summary>
		/// None state for flag enumeration. Not a valid state for usage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("None", 0, "#0000ff", "None state for flag enumeration. Not a valid state for usage")]
		None = 0,
		
		/// <summary>
		/// Not created
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NotCreated", 1, "#0000ff", "Not created")]
		Notcreated = 1,
		
		/// <summary>
		/// Relationship creating
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RelationshipCreating", 3, "#0000ff", "Relationship creating")]
		Relationshipcreating = 4,
	}
}
#pragma warning restore CS1591
