import { test as baseTest, expect } from "@playwright/test";
import { QuestionBankPage } from "../../pages/QuestionBankPage";
import { LoginPage } from "../../pages/LoginPage";
import { WebHelper } from '../../utils/WebHelper';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { Utils } from "../../utils/utils";
import { Common } from '../../selectors/CommonSelector.json';
import { Questionnaire } from '../../selectors/QuestionnaireSelector.json';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { deleteRecord } from '../../utils/APIHelper';
import { EntityLogicalNames } from '../../constants/CommonLogicalNames.json';
import { ProjectService } from '../../services/ProjectService';
import { ManagedListService } from '../../services/ManagedListService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';

//This Fixture is Login the application, Create the Project and create the Managed List
export const test = baseTest.extend<{
  loginPage: LoginPage;
  webhelper: WebHelper;
  questionBankPage: QuestionBankPage;
  guid: string;
  projectName: string;
  managedListName: string;
  questionnaireSetup: void;
}>(
  {
    webhelper: async ({ page }, use) => {
      const webHelper = new WebHelper(page);
      await use(webHelper);
    },

    loginPage: async ({ page, context, webhelper }, use) => {
      const loginPage = new LoginPage(page, context);
      await loginPage.navigateToURL();
      await loginPage.loginToApplication(TestUser.CSUser);
      await webhelper.changeArea(Common.Text.CSUser);
      await use(loginPage);
    },

    projectName: async ({ page }, use) => {
      const projectService = new ProjectService(page);
      const name = "Auto_Project" + Utils.generateGUID();
      await projectService.CreateProject(name);
      const questionnaireService = new Questionnaireservice(page);
      await questionnaireService.addQuestion(TestData.StandardQuestion, Questionnaire.Text.CategoryIntroduction);
      await use(name);
    },

    guid: async ({ page, webhelper, projectName }, use) => {
      const g = await webhelper.fetchRecordGuid(page.url());
      await use(g);
      if (g) {
        try {
          await deleteRecord(EntityLogicalNames.Projects, g);
        } catch (e) {
          console.warn('Failed to delete project during teardown', e);
        }
      }
    },

    managedListName: async ({ page }, use) => {
      const managedListService = new ManagedListService(page);
      const webHelper = new WebHelper(page);
      const name = MLTestData.ManagedListName + Utils.generateText();
      await managedListService.create(name);
      await managedListService.verifyAddedManagedListDetails(name, MLTestData.IsAutoGenerated_No);
      await webHelper.verifySaveButton();
      await managedListService.selectTheManagedList(name);
      await use(name);
    },
  }
);

export default test;
export { expect };
