import { expect, mergeTests } from '@playwright/test';
import { logintest } from '../Fixture/LoginFixture';
import { createproject } from '../Fixture/CreateProjectWithStdQue';
import { LoginToMDAWithTestUser } from '../../utils/Login';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { Utils } from "../../utils/utils";
import { WebHelper } from '../../utils/WebHelper';
import { CommonTestData } from '../../Test Data/CommonTestData.json';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { ProjectService } from '../../services/ProjectService';
import { ManagedListService } from '../../services/ManagedListService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';
import { ManagedList } from '../../selectors/ManagedListSelectors.json';

// Using a LoginFixture and  CreateProjectWithStdQue to handle setup and teardown for all test cases:
// 1. Login the application with CS user
// 2. Create the project and add a question before each test execution.
// 3. Delete the project after the each test case execution

let managedListName = "";
let questionName = "";

// Merges the results of the login test and the create a Project test into a single combined test execution.
const test = mergeTests(logintest, createproject);



// test.beforeEach: Sets up the test environment before every test case.
test.beforeEach(async ({ page,loginPage,projectName,guid }) => {
    const questionnaireService = new Questionnaireservice(page);
    const managedListService = new ManagedListService(page);

    questionName = CommonTestData.QuestionVariableName + Utils.generateText();
    managedListName = MLTestData.ManagedListName + Utils.generateText();

    await test.step('Create and verify the Manage list from Project', async () => {
        await managedListService.create(managedListName);
        await managedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_No);
        await managedListService.selectTheManagedList(managedListName);
    });

    await test.step('Go to Entities tab and Click on the New ML Entity button', async () => {
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
        await managedListService.clickOnNewManagedListEntityButton();
        await managedListService.verifyQuickCreateWindow();
    });
    await test.step('Verify that Answer Text field is mandatory and it is text field that is shown on screen to respondents', async () => {
        await managedListService.verifyAnswerTextIsEditableMandatory();
    });
    await test.step('Verify that ML field is automatically populated', async () => {
        await managedListService.verifyManagedListAutoPopulated(managedListName);
    });
    await test.step('Enter Answer Text', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText);
    });
    await test.step('Click Save & Create New button', async () => {
        await managedListService.clickOnSaveandCreateNewbutton();
    });


});

test("[2547971] Save & Create New ML Entity", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser,loginPage,projectName,guid }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2547971' });

    const managedListService = new ManagedListService(page);

    await test.step('Verify that the Quick create ML Entity side panel remains open and creation fields are empty', async () => {
        await managedListService.verifyQuickCreateWindow();
        await managedListService.verifyQuickCreateWindowFieldsAreEmpty();
    });

});
test("[2548043] Must be cs user able to order the entries in the managed list", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2548043' });
    const webHelper = new WebHelper(page);
    const managedListService = new ManagedListService(page);
    var answerTexts: string[]

    await test.step('Enter another Answer Text', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText1);
    });
    await test.step('Click Save & Create New button', async () => {
        await managedListService.clickOnSaveandCreateNewbutton();
    });
    await test.step('Enter another Answer Text', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText2);
        await webHelper.saveAndCloseQuickCreateRecord();
    });
    await test.step('Verify that the system stores an answer order against each entry in the managed list', async () => {
        answerTexts = await managedListService.getAllAnswerTextsInManagedListEntity();
        await expect(answerTexts[0]).toBe(TestData.AnswerText);
        await expect(answerTexts[1]).toBe(TestData.AnswerText1);
        await expect(answerTexts[2]).toBe(TestData.AnswerText2);
    });

    await test.step('Verify that the user can reorder the existing ML entities', async () => {
        await webHelper.executeDragAndDrop(TestData.AnswerText, TestData.AnswerText1);
        await managedListService.clickonSaveRecord();
        answerTexts = await managedListService.getAllAnswerTextsInManagedListEntity();
        await expect(answerTexts[1]).toBe(TestData.AnswerText);
        await expect(answerTexts[0]).toBe(TestData.AnswerText1);
    });

});

test("[2548103] Scripter user Must be able to view any managed list defined at the project level but not make any changes", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser,loginPage,projectName,guid }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2548103' });
    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const projectService = new ProjectService(page);

    const managedListService = new ManagedListService(page);
    var activeAnswerTexts: string[]


    await test.step('Enter another Answer Text and Click on Save & Create New button', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText1);
        await managedListService.clickOnSaveandCreateNewbutton();
    });
    await test.step('Enter another Answer Text and Click on Save & Create New button', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText2);
        await managedListService.clickOnSaveandCreateNewbutton();
    });

    await test.step('Enter another Answer Text', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText3);
        await webHelper.saveAndCloseQuickCreateRecord();
        activeAnswerTexts = await managedListService.getAllAnswerTextsInManagedListEntity();
    });
    await test.step('Deactivate the Answer', async () => {
        await questionnaireService.deactivateTheAnswer();
        await page.goBack();
    });

    await test.step('Verify the Deactivated Answer In Inactive MangedList Entities', async () => {
        await managedListService.switchToManagedListEntityDropdown(ManagedList.AriaLabel.ActiveManagedListEntities, ManagedList.Text.InactiveManagedListEntities);
        var inActiveEntity = await managedListService.getAllAnswerTextsInManagedListEntity();
        await expect(inActiveEntity[0]).toBe(TestData.AnswerText);
        await webHelper.saveAndCloseRecord();
    });

    await test.step('Add Scripter user to the Project', async () => {
        await projectService.addScripterUserToProject();
    });

    const context = await browser.newContext();
    const scripterUserPage = await context.newPage();
    const newProjectService = new ProjectService(scripterUserPage);
    const scripterUserManagedListService = new ManagedListService(scripterUserPage);
    const scripterUserquestionnaireService = new Questionnaireservice(scripterUserPage);

    await test.step('Login into MDA application with Scripter User', async () => {
        await LoginToMDAWithTestUser(scripterUserPage, TestUser.ScripterUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Open the project ', async () => {
        await newProjectService.searchForProject(projectName);
    });
    await test.step('Navigate to Projects -> Managed Lists tab', async () => {
        await scripterUserquestionnaireService.navigateToTheTab(ManagedList.Tabs.ManagedList);
    });

    await test.step('Verify that the user is able to view defined ML ', async () => {
        await scripterUserManagedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_No);
        await scripterUserManagedListService.selectTheManagedList(managedListName);
        await scripterUserquestionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
    });
    await test.step('Verify that the user is able to view the existing entries in the list, in order, but not make any changes ', async () => {
        var answerTexts: string[] = await scripterUserManagedListService.getAllAnswerTextsInManagedListEntity();
        await expect(answerTexts[0]).toBe(TestData.AnswerText1);
        await expect(answerTexts[1]).toBe(TestData.AnswerText2);

    });

    await test.step('Verify that for the user is available Inactive ML Entities view where all inactive ML entities are listed  ', async () => {
        await scripterUserManagedListService.switchToManagedListEntityDropdown(ManagedList.AriaLabel.ActiveManagedListEntities, ManagedList.Text.InactiveManagedListEntities);
        var inActiveEntity = await scripterUserManagedListService.getAllAnswerTextsInManagedListEntity();
        await expect(inActiveEntity[0]).toBe(TestData.AnswerText);
    });

    await test.step('Verify that for the user is available All ML Entities view where all active and inactive ML entities are listed ', async () => {
        await scripterUserManagedListService.switchToManagedListEntityDropdown(ManagedList.Text.InactiveManagedListEntities, ManagedList.Text.AllManagedListEntities);
        var allActiveEntities = await scripterUserManagedListService.getAllAnswerTextsInManagedListEntity();
        await expect(allActiveEntities[0]).toBe(TestData.AnswerText);
        await expect(allActiveEntities[1]).toBe(TestData.AnswerText1);
        await expect(allActiveEntities[2]).toBe(TestData.AnswerText2);
        await expect(allActiveEntities[3]).toBe(TestData.AnswerText3);

    });

});
test("[2545562]To check if ML can be deleted if its associated with Active questions from QL", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser,projectName,guid,loginPage }) => {
    test.info().annotations.push({ type: 'TestCaseId', description: '2545562' });

    const managedListService = new ManagedListService(page);
    const webHelper = new WebHelper(page);


    await test.step('Enter another Answer Text', async () => {
        await managedListService.fillAnswerText(TestData.AnswerText2);
        await webHelper.saveAndCloseQuickCreateRecord();
        await webHelper.verifySaveButton();
        await page.goBack(); //Navigate to ManagedList tab
    });

    await test.step('Add question to Manage list', async () => {
        await managedListService.addQuestion(managedListName, questionName,false);
        await managedListService.verifyAddedQuestionDetails(TestData.StandardQuest_VariableName1, MLTestData.Location, projectName);
        await webHelper.saveRecord();
    });
    await test.step('Click on Delete button from the Menu in Managed List and Observe the message in Business process error dialogue', async () => {
        await managedListService.deleteTheAnswer();
        await managedListService.VerifyErrorMessage();

    });
});
