import {test } from '../Fixture/LoginAsLibrarianFixture.ts';
import { LoginToMDAWithTestUser } from '../../utils/Login';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { Utils } from "../../utils/utils";
import { DropDownList } from '../../constants/DropDownList.json';
import { WebHelper } from '../../utils/WebHelper';
import { CommonTestData } from '../../Test Data/CommonTestData.json';
import { Questionnaire } from '../../selectors/QuestionnaireSelector.json';
import { QuestionBankservice } from '../../services/QuestionBankService';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { deleteRecord } from '../../utils/APIHelper';
import { EntityLogicalNames } from '../../constants/CommonLogicalNames.json';
import { ProjectService } from '../../services/ProjectService';
import { ManagedListService } from '../../services/ManagedListService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';
import { ManagedList } from '../../selectors/ManagedListSelectors.json';

// Using a LoginAsLibrarianFixture to handle setup and teardown for all test cases:
// 1. Login the application with Librarian user

test("[2485411] Validate The Questions in the Managed List", { tag: ['@Regression', '@ManagedList'] }, async ({ page, browser,loginPage}) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2485411' });

    const webHelper = new WebHelper(page);
    const questionbankService = new QuestionBankservice(page);
    let guidQB: string;

    const projectName = "AUTO_TestPro" + Utils.generateGUID();
    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();
    const managedListName = MLTestData.ManagedListName + Utils.generateText();

    await test.step('Create a Question from Question Bank', async () => {
        await questionbankService.fillMandatoryfieldsInQuestionBank(questionName, DropDownList.QuestionBank.MultiChoice, TestData.QuestionTitle, TestData.QuestionText);
        await questionbankService.clickonSaveRecord();
        await questionbankService.searchDraftQuestionBank(questionName);
    });

    await test.step('Change the Status Reason Draft to Active', async () => {
        await questionbankService.changeStatusReason();
        await questionbankService.selectQuestionBank(questionName);
        guidQB = await webHelper.fetchRecordGuid(page.url());
        await page.close();
    });

    const context = await browser.newContext();
    const csUserPage = await context.newPage();
    const webHelperSecond = new WebHelper(csUserPage);
    const newProjectService = new ProjectService(csUserPage);
    const managedListService = new ManagedListService(csUserPage);
    const questionnaireService = new Questionnaireservice(csUserPage);
    var guid = "";

    await test.step('Login into MDA application', async () => {
        await LoginToMDAWithTestUser(csUserPage, TestUser.CSUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Go to project > Create a Project', async () => {
        await newProjectService.CreateProject(projectName);
        guid = await webHelper.fetchRecordGuid(csUserPage.url());

    });
    await test.step('Add a Question to the Project', async () => {
        await questionnaireService.addQuestion(TestData.StandardQuestion, Questionnaire.Text.CategoryIntroduction);
    });
    await test.step('Create and verify the Manage list from Project', async () => {
        await managedListService.create(managedListName);
        await managedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_No);
    });

    await test.step('Add question to Manage list', async () => {
        await managedListService.addQuestion(managedListName, questionName);
    });
    await test.step('validate the  question added', async () => {
        await managedListService.verifyAddedQuestionDetails(TestData.StandardQuest_VariableName1, MLTestData.Location, projectName);
        await webHelperSecond.saveRecord();
        await managedListService.verifyAddedQuestionDetails(TestData.StandardQuest_VariableName1, MLTestData.Location, projectName);
    });

    await test.step('Delete the Created Project ', async () => {
        await deleteRecord(EntityLogicalNames.Projects, guid);
        await deleteRecord(EntityLogicalNames.QuestionBanks, guidQB);

    });
});

test("[2493099,2493184] To check if ML can be created from QB and ML can be imported to project from QB", { tag: ['@Regression', '@ManagedList'] }, async ({ page, browser,loginPage }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2493099' });
    test.info().annotations.push({ type: 'TestCaseId', description: '2493184' });

    const webHelper = new WebHelper(page);
    const questionbankService = new QuestionBankservice(page);
    let guidQB: string;
    //This is test data to pass into the QB Managed List Reference in Json format
    const jsonData = {
        "sharedLists": [
            {
                "name": "power automate generated",
                "location": "Row",
                "displayOrder": 1
            }
        ]

    };


    const jsonString = JSON.stringify(jsonData, null, 2);
    const projectName = "AUTO_TestPro" + Utils.generateGUID();
    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();

    await test.step('Create a Question from Question Bank', async () => {
        await questionbankService.fillMandatoryfieldsInQuestionBank(questionName, DropDownList.QuestionBank.MultiChoice, TestData.QuestionTitle, TestData.QuestionText);
        await questionbankService.clickonSaveRecord();
        await webHelper.clickonContinueAnyway();
        await questionbankService.searchDraftQuestionBank(questionName);
        guidQB = await webHelper.fetchRecordGuid(page.url());
    });

    await test.step('Change the Status Reason Draft to Active', async () => {
        await questionbankService.fillManagedListReferences(jsonString);
        await questionbankService.changeStatusReason();
        await page.close();
    });

    const context = await browser.newContext();
    const csUserPage = await context.newPage();
    const newProjectService = new ProjectService(csUserPage);
    const managedListService = new ManagedListService(csUserPage);
    const questionnaireService = new Questionnaireservice(csUserPage);
    var guid = "";

    await test.step('Login into MDA application', async () => {
        await LoginToMDAWithTestUser(csUserPage, TestUser.CSUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Go to project > Create a Project', async () => {
        await newProjectService.CreateProject(projectName);
        guid = await webHelper.fetchRecordGuid(csUserPage.url());

    });
    await test.step('Add a Question to the Project', async () => {
        await questionnaireService.addQuestion(questionName, TestData.QuestionTitle);
        await managedListService.clickonSaveRecord();
        await csUserPage.reload();
        await managedListService.clickonSaveRecord();
        await managedListService.clickonSaveRecord();

    });
    await test.step('Create and Validate the Manage list from Project', async () => {
        await managedListService.selectManagedListTab();
        await managedListService.clickonSaveRecord();
        await managedListService.verifyAddedManagedListDetails(jsonData.sharedLists[0].name, MLTestData.IsAutoGenerated_Yes);
    });

    await test.step('Open the Manage list from the grid which is imported from QB ', async () => {
        await managedListService.clickOnManagedList(jsonData.sharedLists[0].name);
    });
    await test.step('validate the  question added', async () => {
        await managedListService.verifyAddedQuestionDetails(questionName, MLTestData.Location, projectName);
    });

    await test.step('Delete the Created Project ', async () => {
        await deleteRecord(EntityLogicalNames.Projects, guid);
        await deleteRecord(EntityLogicalNames.QuestionBanks, guidQB);

    });
});

test("[2553787] Verify that the Manage List Entity cannot be deleted if it is associated to one or more active questions", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser,loginPage }) => {
    test.info().annotations.push({ type: 'TestCaseId', description: '2553787' });

    const webHelper = new WebHelper(page);
    const questionbankService = new QuestionBankservice(page);
    let guidQB: string;
    //This is test data to pass into the QB Managed List Reference in Json format
    const jsonData = {
        "sharedLists": [
            {
                "name": "powerAutomateGenerated",
                "location": "Row",
                "displayOrder": 1
            }
        ]

    };


    const jsonString = JSON.stringify(jsonData, null, 2);
    const projectName = "AUTO_TestPro" + Utils.generateGUID();
    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();
    const managedListName = MLTestData.ManagedListName + Utils.generateText();

    await test.step('Create a Question from Question Bank', async () => {
        await questionbankService.fillMandatoryfieldsInQuestionBank(questionName, DropDownList.QuestionBank.MultiChoice, TestData.QuestionTitle, TestData.QuestionText);
        await questionbankService.clickonSaveRecord();
        await questionbankService.searchDraftQuestionBank(questionName);
    });

    await test.step('Change the Status Reason Draft to Active', async () => {
        await questionbankService.fillManagedListReferences(jsonString);
        await questionbankService.changeStatusReason();
        guidQB = await webHelper.fetchRecordGuid(page.url());
        await page.close();
    });

    const context = await browser.newContext();
    const csUserPage = await context.newPage();
    const webHelperSecond = new WebHelper(csUserPage);
    const newProjectService = new ProjectService(csUserPage);
    const managedListService = new ManagedListService(csUserPage);
    const questionnaireService = new Questionnaireservice(csUserPage);
    const managedListEntityAnswerText2 = TestData.AnswerText1; + Utils.generateText();
    var guid = "";

    await test.step('Login into MDA application', async () => {
        await LoginToMDAWithTestUser(csUserPage, TestUser.CSUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Go to project > Create a Project', async () => {
        await newProjectService.CreateProject(projectName);
        guid = await webHelper.fetchRecordGuid(csUserPage.url());

    });
    await test.step('Add a Question to the Project', async () => {
        await questionnaireService.addQuestion(questionName, TestData.QuestionTitle);
        await managedListService.clickonSaveRecord();
        await csUserPage.reload();
        await managedListService.clickonSaveRecord();
        await managedListService.clickonSaveRecord();

    });

    await test.step('Create and Validate the Manual Manage list from Project', async () => {
        await managedListService.create(managedListName);
        await managedListService.clickonSaveRecord();
    });

    await test.step('associate the added question from project to ML', async () => {
        await managedListService.addQuestion(managedListName, "");
        await managedListService.verifyAddedQuestionDetails(questionName, MLTestData.Location, projectName);
        await webHelperSecond.saveRecord();
    });

    await test.step('Go to Entities tab and Click on the New ML Entity button', async () => {
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
        await managedListService.clickOnNewManagedListEntityButton();
        await managedListService.verifyQuickCreateWindow();
        await managedListService.fillAnswerText(managedListEntityAnswerText2);
        await webHelperSecond.saveAndCloseQuickCreateRecord();
        await webHelperSecond.verifySaveButton();
    });

    await test.step('Click on Delete button on ML Entity and Observe the message in Business process error dialogue', async () => {
        await managedListService.deleteTheAnswer();
        await managedListService.VerifyErrorMessage();

    });

});


