import { expect, mergeTests } from '@playwright/test';
import { logintest } from '../Fixture/LoginFixture';
import { createproject } from '../Fixture/CreateProjectWithStdQue';
import { LoginToMDAWithTestUser } from '../../utils/Login';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { Utils } from "../../utils/utils";
import { DropDownList } from '../../constants/DropDownList.json';
import { WebHelper } from '../../utils/WebHelper';
import { CommonTestData } from '../../Test Data/CommonTestData.json';
import { Questionnaire } from '../../selectors/QuestionnaireSelector.json';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { ProjectService } from '../../services/ProjectService';
import { ManagedListService } from '../../services/ManagedListService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';
import { ManagedList } from '../../selectors/ManagedListSelectors.json';

// Merges the results of the login test and the create a Project test into a single combined test execution.
const test = mergeTests(logintest, createproject);


// Using a LoginFixture and  CreateProjectWithStdQue to handle setup and teardown for all test cases:
// 1. Login the application with CS user
// 2. Create the project and add a question before each test execution.
// 3. Delete the project after the each test case execution

test("[2486751] To verify that Managed list placeholder order can be adjusted via drag and drop.in questionnaire line - Manage list tab", { tag: ['@Regression', '@ManagedList'] }, async ({ page, browser, loginPage, projectName }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2486751' });

    const projectService = new ProjectService(page);
    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const managedListService = new ManagedListService(page);
    const managedListName1 = MLTestData.ManagedListName + "1";
    const managedListName2 = MLTestData.ManagedListName + "2";

    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();

    await test.step('Create 3 Manage lists from Project', async () => {
        for (let i = 1; i < 4; i++) {
            const mlName = MLTestData.ManagedListName + `${i}`;
            await managedListService.create(mlName);
            await managedListService.verifyAddedManagedListDetails(mlName, MLTestData.IsAutoGenerated_No);
            await managedListService.addQuestion(mlName, questionName);
            await webHelper.saveAndCloseRecord();
        }
        await webHelper.saveAndCloseRecord();
    });
    await test.step('Now share a project to scripter user from User management', async () => {
        await webHelper.verifySaveButton()
        await projectService.addScripterUserToProject();
        await webHelper.saveRecord();
    });
    await test.step('Now go to Manage list tab from Master questionnaire line', async () => {
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await questionnaireService.clickonEditbutton();
        await questionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);
    });

    await test.step('Now drag and drop reorder the manage list between the positions and save', async () => {
        await webHelper.verifySaveButton()
        var managedList: string[] = await managedListService.getManagedListNames();
        await webHelper.executeDragAndDrop(managedListName1, managedListName2);
        await webHelper.verifySaveButton();
        await webHelper.saveRecord();
        await managedListService.verifyDragAndDropElements(managedList[0], managedList[1]);
        await page.close();
    });

    const context = await browser.newContext();
    const scripterUserPage = await context.newPage();
    const webHelperSecond = new WebHelper(scripterUserPage);
    const newProjectService = new ProjectService(scripterUserPage);
    const scripterUserManagedListService = new ManagedListService(scripterUserPage);
    const scripterUserquestionnaireService = new Questionnaireservice(scripterUserPage);

    await test.step('Login into MDA application with Scripter user', async () => {
        await LoginToMDAWithTestUser(scripterUserPage, TestUser.ScripterUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Open the project ', async () => {
        await newProjectService.searchForProject(projectName);
    });

    await test.step('Now go to Manage list tab from Master questionnaire line and Manage list should be visible in the same order as CS user reordered it', async () => {
        await scripterUserquestionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await scripterUserquestionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await scripterUserquestionnaireService.clickonEditbutton();
        await scripterUserquestionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);

    });
    await test.step('Manage list should be visible in the same order as CS user reordered it', async () => {
        var managedList: string[] = await scripterUserManagedListService.getManagedListNames();
        await expect(managedList[0]).toBe(managedListName2);
        await expect(managedList[1]).toBe(managedListName1);
    });
    await test.step('Try to Reorder the manage list from Questionnaire line', async () => {
        var managedList: string[] = await scripterUserManagedListService.getManagedListNames();
        await webHelperSecond.executeDragAndDrop(managedListName2, managedListName1);
        await webHelperSecond.verifySaveButton();
        await webHelperSecond.saveRecord();
        await scripterUserManagedListService.verifyDragAndDropElements(managedList[1], managedList[0]);

    });

});

test("[2493219] To check the visibility restrictions of manage list for scripters", { tag: ['@Regression', '@ManagedList'] }, async ({ page, browser, loginPage, projectName }) => {
    test.info().annotations.push({ type: 'TestCaseId', description: '2493219' });

    const projectService = new ProjectService(page);
    const webHelper = new WebHelper(page);
    const managedListService = new ManagedListService(page);
    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();

    await test.step('Create 3 Manage lists from Project', async () => {
        for (let i = 0; i < 3; i++) {
            const mlName = MLTestData.ManagedListName + `${i}`;
            await managedListService.create(mlName);
            await managedListService.verifyAddedManagedListDetails(mlName, MLTestData.IsAutoGenerated_No);
            await managedListService.addQuestion(mlName, questionName);
            await webHelper.saveAndCloseRecord();
        }
        await webHelper.saveAndCloseRecord();
    });
    await test.step('Now share a project to scripter user from User management', async () => {
        await webHelper.verifySaveButton()
        await projectService.addScripterUserToProject();
        await webHelper.saveRecord();
    });

    const context = await browser.newContext();
    const scripterUserPage = await context.newPage();
    const webHelperSecond = new WebHelper(scripterUserPage);
    const newProjectService = new ProjectService(scripterUserPage);
    const scripterUserManagedListService = new ManagedListService(scripterUserPage);
    const scripterUserquestionnaireService = new Questionnaireservice(scripterUserPage);

    await test.step('Login into MDA application with Scripter User', async () => {
        await LoginToMDAWithTestUser(scripterUserPage, TestUser.ScripterUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Open the project ', async () => {
        await newProjectService.searchForProject(projectName);
    });

    await test.step('Now go to Manage list tab from Master questionnaire line and Manage list should be visible in the same order as CS user reordered it', async () => {
        await scripterUserquestionnaireService.navigateToTheTab(Questionnaire.Tabs.Questionnaire);
        await scripterUserquestionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await scripterUserquestionnaireService.clickonEditbutton();
        await scripterUserquestionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);

    });
    await test.step('Go to Questionnaire line from master question and check Manage list tab', async () => {
        await scripterUserManagedListService.validatebutton(ManagedList.Text.NewQuestionnaireLineManagedList, false);
        await webHelper.saveAndCloseRecord();
        await scripterUserquestionnaireService.navigateToTheTab(Questionnaire.Tabs.ManagedLists);
        await scripterUserManagedListService.validatebutton(ManagedList.Text.NewManagedList, false);

    });
});

test("[2545903] To verify if QB imported ML name can be edited from QL - ML tab (QL level)", { tag: ['@Regression', '@ManagedList'] }, async ({ page, loginPage, projectName }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2545903' });

    const managedListName = MLTestData.ManagedListName + Utils.generateText();
    const managedListService = new ManagedListService(page);


    await test.step('Create and verify the Manage list from Project', async () => {
        await managedListService.create(managedListName);
        await managedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_No);
    });
    await test.step('Open the Manage list from the grid which is imported from QB ', async () => {
        await managedListService.clickOnManagedList(managedListName);
    });
    await test.step('Check if ML Name text field is locked and disabled', async () => {
        await managedListService.verifyMLNameTextFieldIsEditable(true);
    });
});