import { expect, mergeTests } from '@playwright/test';
import { LoginToMDAWithTestUser } from '../../utils/Login';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { Utils } from "../../utils/utils";
import { DropDownList } from '../../constants/DropDownList.json';
import { WebHelper } from '../../utils/WebHelper';
import { CommonTestData } from '../../Test Data/CommonTestData.json';
import { Questionnaire } from '../../selectors/QuestionnaireSelector.json';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { ManagedListService } from '../../services/ManagedListService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';
import { logintest } from '../Fixture/LoginFixture';
import { createproject } from '../Fixture/CreateProjectWithStdQue';

// Merges the results of the login test and the create a Project test into a single combined test execution.
const test = mergeTests(logintest, createproject);


// Using a LoginFixture and  CreateProjectWithStdQue to handle setup and teardown for all test cases:
// 1. Login the application with CS user
// 2. Create the project and add a question before each test execution.
// 3. Delete the project after the each test case execution

test("[2486486] To verify if a question can be assigned to a manage list from multiple location combinations", { tag: ['@Regression', '@ManagedList'] }, async ({ page, browser, loginPage, projectName }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2486486' });

    const webHelper = new WebHelper(page);
    const managedListService = new ManagedListService(page);
    const questionnaireService = new Questionnaireservice(page);

    const questionName = CommonTestData.QuestionVariableName + Utils.generateText();
    const managedListName = MLTestData.ManagedListName + Utils.generateText();


    await test.step('Create and verify the Manage list from Project', async () => {
        await managedListService.create(managedListName);
        await managedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_No);
    });

    await test.step('Add question to Manage list', async () => {
        await managedListService.addQuestion(managedListName, questionName);
    });

    await test.step('validate the  question added', async () => {
        await managedListService.verifyAddedQuestionDetails(TestData.StandardQuest_VariableName1, MLTestData.Location, projectName);
        await webHelper.saveRecord();
        await managedListService.verifyAddedQuestionDetails(TestData.StandardQuest_VariableName1, MLTestData.Location, projectName);
    });

    await test.step('Edit the location and verify the location is edited sucessfully from Managed List', async () => {
        await managedListService.editQuestionLocationFromML(TestData.StandardQuest_VariableName1, MLTestData.Location_Column);
        await webHelper.saveRecord();
        await webHelper.clickGoBackArrow();
        await webHelper.verifySaveButton();
    });

    await test.step('Edit the location and verify the location is edited sucessfully from Questionnaire line MDA', async () => {
        await webHelper.clickOnTab(Questionnaire.Tabs.Questionnaire);
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await webHelper.clickonStartWithText("Edit");
        await managedListService.editManagedListLocationFromQL(managedListName, MLTestData.Location);
    });

});


