import { expect, mergeTests } from '@playwright/test';
import { logintest } from '../Fixture/LoginFixture';
import { createproject } from '../Fixture/CreateProjectWithAutoGenML';
import { Utils } from "../../utils/utils";
import { DropDownList } from '../../constants/DropDownList.json';
import { WebHelper } from '../../utils/WebHelper';
import { CommonTestData } from '../../Test Data/CommonTestData.json';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { ProjectService } from '../../services/ProjectService';
import { ManagedListService } from '../../services/ManagedListService';
import { TestData as MLTestData } from '../../Test Data/ManagedListData.json';
import { ManagedList } from '../../selectors/ManagedListSelectors.json';
import { StudyTestData } from '../../Test Data/StudyData.json';
import { StudyService } from '../../services/StudyService';

// Using a LoginFixture and CreateProjectWithAutoGenML to handle setup and teardown for all test cases:
// 1. Login the application with CS user
// 2. Create the project and add a question before each test execution.
// 3. Delete the project after the each test case execution

let managedListName = "";
let questionName = "";
let studyName = "";
let newStudyVersionName2 = "";
let newStudyVersionName3 = "";

// Merges the results of the login test and the create a Project test into a single combined test execution.
const test = mergeTests(logintest, createproject);

//  Executes setup steps before each test case to prepare the required environment.
test.beforeEach(async ({ page, loginPage, projectName, guid }) => {
    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const projectService = new ProjectService(page);
    const managedListService = new ManagedListService(page);
    const studyService = new StudyService(page);

    questionName = CommonTestData.QuestionVariableName + Utils.generateText();
    studyName = StudyTestData.StudyName + Utils.generateGUID();
    managedListName = MLTestData.AutoGen_MLName;
    newStudyVersionName2 = studyName + '_New Version2';
    newStudyVersionName3 = studyName + '_New Version3';


    await test.step('Create and Validate the Manage list from Project', async () => {
        await managedListService.clickonSaveRecord();
        await managedListService.selectManagedListTab();
        await managedListService.clickonSaveRecord();
        await managedListService.verifyAddedManagedListDetails(managedListName, MLTestData.IsAutoGenerated_Yes);
    });

    await test.step('Navigate to ML and add multiple ML entities', async () => {
        await managedListService.selectTheManagedList(managedListName);
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
        const answerText: string[] = [TestData.AnswerText, TestData.AnswerText1, TestData.AnswerText2]
        for (let i = 0; i < answerText.length; i++) {
            await webHelper.verifySaveButton();
            await managedListService.clickOnNewManagedListEntityButton();
            await managedListService.verifyQuickCreateWindow();
            await managedListService.fillAnswerText(answerText[i]);
            await webHelper.saveAndCloseQuickCreateRecord();
            await webHelper.saveRecord();
        }

        await webHelper.saveAndCloseRecord();
    });
    await test.step('Create a Draft study ', async () => {
        await projectService.addScripterUserToProject();
        await studyService.CreateNewStudy(studyName, StudyTestData.Category, StudyTestData.FieldWorkMarket,
            StudyTestData.MaconomyJobNumber, StudyTestData.ProjectOperationsURL, StudyTestData.ScripterNotes);
        await webHelper.handleConfirmationPopup();
        await studyService.ValidateInitialDraftStateStudy();
    });

    await test.step('Update study from Draft to Ready for Scritping', async () => {
        await studyService.updateStudyStatus(DropDownList.Status.ReadyForScripting);
        await webHelper.saveRecord();
        await webHelper.verifyNewButton();
        await webHelper.clickGoBackArrow();
    });
    await test.step('Navigate to Manage List and open ML', async () => {
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.ManagedList);
        await managedListService.selectTheManagedList(managedListName);
    });

});

test("[2548013] Verify that when Manage List entities are reordered, the change log is generated.", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser, loginPage, projectName, guid }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2548013' });
    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const managedListService = new ManagedListService(page);
    const studyService = new StudyService(page);


    await test.step('On the Manage List, navigate to Entities tab and add new Manage List Entity', async () => {
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
        await webHelper.executeDragAndDrop(TestData.AnswerText, TestData.AnswerText1);
        await managedListService.clickonSaveRecord();
        var answerTexts: string[] = await managedListService.getAllAnswerTextsInManagedListEntity();
        await expect(answerTexts[1]).toBe(TestData.AnswerText);
        await expect(answerTexts[0]).toBe(TestData.AnswerText1);
        await webHelper.verifySaveButton();
        await webHelper.saveAndCloseRecord();
    });


    await test.step('Create new version of the Study and move it to Ready for Scripting', async () => {
        await studyService.openStudy(studyName);
        await studyService.createNewStudyVersion(newStudyVersionName2);
        await webHelper.saveRecord();
        await studyService.updateStudyStatus(DropDownList.Status.ReadyForScripting);

    });
    await test.step('Verify that when Manage List entities are added, the change log is generated', async () => {
        await studyService.validateFieldChangeStudyChangeLogs(MLTestData.ReorderFieldChange);
    });

});

test("[2548015] Verify that when Manage List entities are reactivated, the change log is generated..", { tag: ['@Regression', '@MLEntity'] }, async ({ page, browser, loginPage, projectName, guid }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2548015' });
    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const managedListService = new ManagedListService(page);
    const studyService = new StudyService(page);


    await test.step('Deactivate the entity', async () => {
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
        await questionnaireService.deactivateTheAnswer();
        await page.waitForTimeout(2000);
        await page.goBack();
        await webHelper.verifySaveButton();
        await webHelper.clickGoBackArrow();
    });

    await test.step('Create new version of the Study and move it to Ready for Scripting', async () => {
        await studyService.openStudy(studyName);
        await studyService.createNewStudyVersion(newStudyVersionName2);
        await webHelper.saveRecord();
        await studyService.updateStudyStatus(DropDownList.Status.ReadyForScripting);
        await studyService.ValidateStudyStatusReason(DropDownList.Status.ReadyForScripting);
        await webHelper.saveRecord();
        await webHelper.verifyNewButton();
        await webHelper.clickGoBackArrow();
        await webHelper.saveRecord();
        await webHelper.verifyNewButton();
        await webHelper.clickGoBackArrow();
    });

    await test.step('On the Manage List, navigate to Entities tab and remove one of the entities', async () => {
        await managedListService.selectManagedListTab();
        await managedListService.selectTheManagedList(managedListName);
        await questionnaireService.navigateToTheTab(ManagedList.Tabs.Entities);
        await managedListService.switchToManagedListEntityDropdown(ManagedList.AriaLabel.ActiveManagedListEntities, ManagedList.Text.InactiveManagedListEntities);
        await questionnaireService.activateTheAnswer();
        await webHelper.verifySaveButton();
        await page.goBack();
        await webHelper.verifySaveButton();
        await webHelper.clickGoBackArrow();
    });

    await test.step('Create new version of the Study and move it to Ready for Scripting', async () => {
        await studyService.openStudy(newStudyVersionName2);
        await studyService.createNewStudyVersion(newStudyVersionName3);
        await webHelper.saveRecord();
        await studyService.updateStudyStatus(DropDownList.Status.ReadyForScripting);
    });
    await test.step('Verify that when Manage List entities are added, the change log is generated', async () => {
        const addEntity = TestData.AutoGenMLQuestion + ',' + 'Managed List Entity added';
        const changeLogs: string[] = [addEntity]
        await studyService.validateStudyChangeLogs(changeLogs);
    });
});