import { expect, test } from '../Fixture/AddingStandardQuestionFixture.ts';
import { Utils } from "../../utils/utils";
import { LoginToMDAWithTestUser } from '../../utils/Login';
import { TestUser, AppName, AppId } from '../../constants/TestUsers.json';
import { DropDownList } from '../../constants/DropDownList.json';
import { WebHelper } from '../../utils/WebHelper';
import { Questionnaireservice } from '../../services/QuestionnaireService';
import { TestData } from '../../Test Data/QuestionnnaireData.json';
import { ProjectService } from '../../services/ProjectService';
import { ManagedListService } from '../../services/ManagedListService';
import { ManagedList } from '../../selectors/ManagedListSelectors.json';
import { StudyTestData } from '../../Test Data/StudyData.json';
import { StudyService } from '../../services/StudyService';
import { Questionnaire } from '../../selectors/QuestionnaireSelector.json';


// Using a AddingStandardQuestionFixture  to handle setup and teardown for all test cases:
// 1. Create the project and add a question before each test execution.
// 2. Delete the project after the each test case execution


test("[2614578]  Check AI is generating Answer Codes when a custom answer is created in a Standard question", { tag: ['@Regression', '@ManagedList'] }, async ({ loginPage, page, browser, projectName, guid }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2614578' });

    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const projectService = new ProjectService(page);
    const managedListService = new ManagedListService(page);


    await test.step('Edit a standard question and add custom answers', async () => {
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await questionnaireService.clickonEditbutton();
        await projectService.navigateToAnswersTabFromMasterQuestionnaireLines();
        await webHelper.clickOnCommandBarBtn(ManagedList.Button.AddNewAnswer);
        await managedListService.fillAnswerText(TestData.AnswerText);
        await webHelper.verifyFieldReadonly(ManagedList.AriaLabel.AnswerCode);
        await webHelper.saveAndCloseRecord();
    });

    await test.step('Check the Answer code is generated by AI', async () => {
        const aiAnswerCode: string[] = await questionnaireService.getAICodeForAnswerText(Questionnaire.CSS.AnswerCode);
        await expect(aiAnswerCode[2]).not.toBeNull();

    });


});

test("[2614591]   Verify scripter user can edit the custom answer of a Standard question when a study is in Draft or Ready For Scripting state", { tag: ['@Regression', '@ManagedList'] }, async ({ loginPage, page, browser, projectName, guid }) => {

    test.info().annotations.push({ type: 'TestCaseId', description: '2614591' });

    const webHelper = new WebHelper(page);
    const questionnaireService = new Questionnaireservice(page);
    const projectService = new ProjectService(page);
    const managedListService = new ManagedListService(page);
    const studyService = new StudyService(page);
    let aiAnswerCode: string[];

    const studyName1 = StudyTestData.StudyName + Utils.generateGUID();
    const studyName2 = StudyTestData.StudyName + Utils.generateGUID();

    await test.step('Edit a standard question and add custom answers', async () => {
        await questionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await questionnaireService.clickonEditbutton();
        await projectService.navigateToAnswersTabFromMasterQuestionnaireLines();
        await webHelper.clickOnCommandBarBtn(ManagedList.Button.AddNewAnswer);
        await webHelper.verifySaveButton();
        await webHelper.clickOnHideFormButton();
        await managedListService.fillAnswerText(TestData.AnswerText6);
        await webHelper.verifyFieldReadonly(ManagedList.AriaLabel.AnswerCode);
        await webHelper.saveRecord();
        await webHelper.clickGoBackArrow();
    });

    await test.step('Check the Answer code is generated by AI', async () => {
        aiAnswerCode = await questionnaireService.getAICodeForAnswerText(Questionnaire.CSS.AnswerCode);
        await expect(aiAnswerCode[2].length).toBeGreaterThan(0);
        await expect(aiAnswerCode[2]).not.toBeNull();
        await webHelper.saveAndCloseRecord();

    });
    await test.step('Create studies with Draft, Ready for Scripting status', async () => {
        await projectService.addScripterUserToProject();
        await studyService.CreateNewStudy(studyName1, StudyTestData.Category, StudyTestData.FieldWorkMarket,
            StudyTestData.MaconomyJobNumber, StudyTestData.ProjectOperationsURL, StudyTestData.ScripterNotes);
        await webHelper.handleConfirmationPopup();
        await studyService.ValidateInitialDraftStateStudy();
        await studyService.updateStudyStatus(DropDownList.Status.ReadyForScripting);
        await webHelper.saveRecord();
        await webHelper.verifyNewButton();
        await webHelper.clickGoBackArrow();
        await studyService.CreateNewStudy(studyName2, StudyTestData.Category, StudyTestData.FieldWorkMarket,
            StudyTestData.MaconomyJobNumber, StudyTestData.ProjectOperationsURL, StudyTestData.ScripterNotes);
        await webHelper.handleConfirmationPopup();
        await studyService.ValidateInitialDraftStateStudy();
        await webHelper.saveRecord();
        await webHelper.verifyNewButton();
        await webHelper.clickGoBackArrow();
    });


    const context = await browser.newContext();
    const scripterUserPage = await context.newPage();
    const webHelperSecond = new WebHelper(scripterUserPage);
    const newProjectService = new ProjectService(scripterUserPage);
    const scripterUserManagedListService = new ManagedListService(scripterUserPage);
    const scripterUserquestionnaireService = new Questionnaireservice(scripterUserPage);

    await test.step('Login into MDA application with Scripter User', async () => {
        await LoginToMDAWithTestUser(scripterUserPage, TestUser.ScripterUser, AppId.UC1, AppName.UC1);
    });
    await test.step('Open the project ', async () => {
        await newProjectService.searchForProject(projectName);
    });
    await test.step('Open standard question where custom answers are added and Navigate to Answers tab ', async () => {
        await scripterUserquestionnaireService.expandQuestionnaire(DropDownList.QuestionBank.SmallTextInput);
        await scripterUserquestionnaireService.clickonEditbutton();
        await newProjectService.navigateToAnswersTabFromMasterQuestionnaireLines();
    });
    await test.step('Edit the Answer codes and Validate the Updated Answer Code ', async () => {
        await scripterUserManagedListService.selectAnswerTextByLabel(TestData.AnswerText6);
        await scripterUserquestionnaireService.updateAnswerCode(TestData.Question2, false);
        const newAnswerCode: string[] = await scripterUserquestionnaireService.getAICodeForAnswerText(Questionnaire.CSS.scripterUserAnserCode);
        await expect(newAnswerCode[2]).not.toBe(aiAnswerCode[2]);

    });
});

