namespace Api.Features.QuestionBank;

// Get all questions
public record GetQuestionBankItemsResponse(
    Guid Id,
    string VariableName,
    int Version,
    string? QuestionType,
    string? QuestionText,
    string? Classification,
    bool IsDummy,
    string? QuestionTitle,
    string? Status,
    string? StatusReason,
    string? Methodology,
    DateTime CreatedOn,
    string? CreatedBy
);

// Get question by ID
public record GetQuestionBankItemByIdResponse(
    Guid Id,
    string VariableName,
    int Version,
    string? QuestionType,
    string? QuestionText,
    string? Classification,
    bool IsDummy,
    string? QuestionTitle,
    string? Status,
    string? StatusReason,
    string? Methodology,
    string? DataQualityTag,
    int? RowSortOrder,
    int? ColumnSortOrder,
    int? AnswerMin,
    int? AnswerMax,
    string? QuestionFormatDetails,
    string? ScraperNotes,
    string? CustomNotes,
    string? MetricGroup,
    string? TableTitle,
    string? QuestionRationale,
    string? SingleOrMulticode,
    string? ManagedListReferences,
    bool IsTranslatable,
    bool IsHidden,
    bool IsQuestionActive,
    bool IsQuestionOutOfUse,
    int? AnswerRestrictionMin,
    int? AnswerRestrictionMax,
    string? RestrictionDataType,
    string? RestrictedToClient,
    string? AnswerTypeCode,
    bool IsAnswerRequired,
    string? ScalePoint,
    string? ScaleType,
    string? DisplayType,
    string? InstructionText,
    Guid? ParentQuestionId,
    string? QuestionFacet,
    DateTime CreatedOn,
    string? CreatedBy,
    DateTime? ModifiedOn,
    string? ModifiedBy,
    List<QuestionAnswerResponse> Answers
);

// Create question
public record CreateQuestionBankItemRequest(
    string VariableName,
    int Version,
    string? QuestionType,
    string? QuestionText,
    string? Classification,
    bool IsDummy,
    string? QuestionTitle,
    string? Status,
    string? StatusReason,
    string? Methodology,
    string? DataQualityTag,
    int? RowSortOrder,
    int? ColumnSortOrder,
    int? AnswerMin,
    int? AnswerMax,
    string? QuestionFormatDetails,
    string? ScraperNotes,
    string? CustomNotes,
    string? MetricGroup,
    string? TableTitle,
    string? QuestionRationale,
    string? SingleOrMulticode,
    string? ManagedListReferences,
    bool IsTranslatable,
    bool IsHidden,
    bool IsQuestionActive,
    bool IsQuestionOutOfUse,
    int? AnswerRestrictionMin,
    int? AnswerRestrictionMax,
    string? RestrictionDataType,
    string? RestrictedToClient,
    string? AnswerTypeCode,
    bool IsAnswerRequired,
    string? ScalePoint,
    string? ScaleType,
    string? DisplayType,
    string? InstructionText,
    Guid? ParentQuestionId,
    string? QuestionFacet
);

public record CreateQuestionBankItemResponse(
    Guid Id,
    string VariableName,
    int Version
);

// Update question
public record UpdateQuestionBankItemRequest(
    string VariableName,
    int Version,
    string? QuestionType,
    string? QuestionText,
    string? Classification,
    bool IsDummy,
    string? QuestionTitle,
    string? Status,
    string? StatusReason,
    string? Methodology,
    string? DataQualityTag,
    int? RowSortOrder,
    int? ColumnSortOrder,
    int? AnswerMin,
    int? AnswerMax,
    string? QuestionFormatDetails,
    string? ScraperNotes,
    string? CustomNotes,
    string? MetricGroup,
    string? TableTitle,
    string? QuestionRationale,
    string? SingleOrMulticode,
    string? ManagedListReferences,
    bool IsTranslatable,
    bool IsHidden,
    bool IsQuestionActive,
    bool IsQuestionOutOfUse,
    int? AnswerRestrictionMin,
    int? AnswerRestrictionMax,
    string? RestrictionDataType,
    string? RestrictedToClient,
    string? AnswerTypeCode,
    bool IsAnswerRequired,
    string? ScalePoint,
    string? ScaleType,
    string? DisplayType,
    string? InstructionText,
    Guid? ParentQuestionId,
    string? QuestionFacet
);

public record UpdateQuestionBankItemResponse(
    Guid Id,
    string VariableName,
    int Version
);
