namespace Kantar.StudyDesignerLite.Migrations.Migrations.Configurations;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kantar.StudyDesignerLite.Migrations.Enums;
using Kantar.StudyDesignerLite.Migrations.Migrations;
using Kantar.StudyDesignerLite.Migrations.Models;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

public class ConfigQuestionsAIPromptUpdate : FixDataMigration
{
    public override int ExecutionOrder => 5;
    public override string Description => "Update ktr_configurationquestion table AI Prompt column";
    
    private readonly Dictionary<string, string> _replaces = new()
    {
        { "Which gender question would you like to use?", "Binary Gender Question: This approach typically involves offering two options for respondents to identify their gender, usually ''Male'' and ''Female''. This traditional method is straightforward but does not accommodate those who identify outside the binary framework, such as non-binary, genderqueer, or other gender identities. - Inclusive Gender Question: This approach is more comprehensive and allows respondents to identify their gender beyond the traditional male and female options. It often includes additional categories such as ''Non-binary'', ''Prefer not to say'' or an open-ended option where respondents can describe their gender identity in their own words. This approach acknowledges and respects the diversity of gender identities. The inclusive gender question is recommended but not universally set as the default for Brand Guidance. It cannot be used in markets where it is socially unacceptable. In such cases, alternative gender questions may be required to align with local norms and practices. If the answer cannot be retrieved from the text, then use ''Inclusive'' by default." },
        { "What type of category is this survey for?", "CPG (Consumer Packaged Goods): These are products that are sold quickly at a relatively low cost. Examples include food, beverages, toiletries, confectionery, cosmetics, over the counter drugs, dry goods and other consumables. CPGs are generally characterized by frequent purchase cycles as they are everyday items that consumers regularly buy. Non-CPG - Frequent Purchase Cycle: This refers to non-consumable goods that are purchased frequently. These products might not be everyday consumables like CPGs, but they are still bought regularly. An example could be a digital subscriptions or software services that, while not consumable in the same way as food, are still purchased on a regular basis. Non-CPG - Infrequent Purchase Cycle: These are non-consumable goods that are purchased less frequently. They might include durable goods or products that have a longer lifespan, such as electronics, furniture, or appliances. These items are typically purchased less often due to their durability or higher cost. - null: The answer cannot be retrieved from the text." },
        { "How would you like unaided awareness to be coded?", "1. AI Coding: This option utilizes artificial intelligence to automatically code responses. It leverages machine learning algorithms to categorize open-ended responses efficiently, reducing manual effort and potential human error. 2. Respondent Self-Code: In this approach, respondents categorize their own responses using predefined options. This method allows for direct input from the respondent, ensuring that their perspective is accurately captured without interpretation by researchers. 3. No Coding: Choosing this option means that the unaided awareness responses will remain in their raw form without being categorized or coded. This approach might be used when qualitative analysis of verbatim responses is preferred or when coding is not necessary for the study''s objectives." },
        { "Which additional standard screening questions would you like to use?", "Chief Shopper: This screening question is designed to identify the primary individual responsible for purchasing decisions in a household or for a particular category of products. The chief shopper is typically the person who makes the most significant purchasing decisions, manages shopping activities, and thus influences the purchase of specific brands or categories. Including this question helps ensure that the survey reaches the most relevant respondents who have the authority and experience to provide meaningful insights about shopping behaviors and preferences. - Category Usage: This screening question aims to determine whether the respondent uses or consumes a particular category of products. It helps filter out respondents who do not engage with the category in question, ensuring that the survey focuses on individuals who have relevant experiences and opinions about the products being studied. By understanding category usage, researchers can better tailor the survey to the right audience and obtain more accurate data regarding product usage patterns and consumer preferences. - null: The answer cannot be retrieved from the text." },
        { "Which age question(s) would you like to use?", "Exact age and age bands: This question type asks respondents to provide their exact age along with selecting from predefined age bands. It allows for precise demographic segmentation while also categorizing respondents into broader age groups for analysis. Choose this option when detailed age data is needed for in-depth demographic analysis and when both specific and general age categories are required by the study. You will typically find this requirement in the Survey Design Section or Demographics and Screening Criteria, which specifies the level of detail needed in demographic data collection. If not mentioned explicitly, retrieve it from a context, for example ''age range of 20-40'' refers to ''Exact age and age bands'' - Expandable age bands: This option provides respondents with the flexibility to select from a range of age bands, which can be expanded or collapsed based on their preferences. It allows for a more tailored approach to age categorization, accommodating various demographic needs. Opt for this when the study requires adaptable age groupings that can be modified based on evolving study needs or when the client prefers flexible demographic segmentation. Look for this in the Project Scope and Objectives section, which may outline requirements for flexibility in survey design and demographic data collection. - Age bands only: This question type focuses solely on age bands without asking for the exact age. Respondents select from predefined categories, which simplifies the response process but may limit detailed demographic insights. Select this option when the study''s objectives can be met with broad age segments and there is no need for detailed age data. This requirement is often located in the Demographics and Screening Criteria where the level of detail in data collection is specified. - null: The answer cannot be retrieved from the text." },
        { "Which of the following optional MDS insights would you like to include?", "In the context of market research using the Meaningfully Different Salient (MDS) framework, the optional insights Pricing Power, Future Power, and Activation Power provide different perspectives on a brand''s market position and potential. Here is an explanation of each option: - Pricing Power: This insight evaluates a brand''s ability to command a premium price based on consumer perceptions and willingness to pay more for its products or services. It reflects how well a brand can maintain its pricing strategy without losing customers, indicating strong brand equity and perceived value. - Pricing Power is useful for understanding the financial strength and market leverage a brand holds. - Future Power: This insight assesses a brand''s potential for growth and future success. It considers factors such as innovation, consumer trends, and brand adaptability to predict how well the brand is likely to perform in the future market landscape. Future Power helps in strategic planning and investment decisions by highlighting areas where a brand can capitalize on upcoming opportunities. - Activation Power: This insight focuses on a brand''s ability to convert awareness and interest into actual sales or consumer action. It measures how effectively a brand can activate its consumer base through marketing and promotional efforts. Activation Power is critical for assessing the effectiveness of marketing campaigns and understanding how well a brand engages its target audience to drive conversions. Each of these insights provides valuable information for tailoring strategies to enhance brand equity and market performance. - null: The answer cannot be retrieved from the text." },
        { "Which of the following optional modules would you like to include?", "1. Category Reminder Screen: Used when custom screener questions will be added. It helps in reminding respondents about the category under study, ensuring their responses are contextually relevant. 2. Understanding Which Brands a Consumer is Likely to Select From (Consideration): Focuses on identifying the brands consumers are considering for purchase, highlighting brand preference and potential market competition. 3. Understanding Recent Purchasing Behaviour (Bought Last): Analyzes recent purchase activities of consumers, providing insights into current market dynamics and consumer loyalty. 4. Understand Consumer Views on Brand Switching in the Category (Customer Typology): Examines consumer attitudes towards switching brands, helping to understand loyalty and the factors influencing brand change. 5. Understand Consumer Satisfaction with Brand Choice in the Category (Category Evaluation): Measures consumer satisfaction with their chosen brands, indicating brand performance and consumer contentment. 6. Understanding of Consumer Needs That Bring Them Into the Category (Category Entry Points): Investigates the needs and motivations that lead consumers to engage with a category, providing insights into market entry strategies. 7. Understanding How Market Factors Affect Purchase Decisions (Market Factors): Explores external factors influencing consumer purchase decisions, such as economic conditions or competitive actions. 8. Understanding Consumer Perceptions of Different Brand Attributes (Brand Imagery): Analyzes how consumers perceive various brand attributes, informing brand positioning and marketing strategies. 9. Understanding Brand Advocacy (NPS): Measures the likelihood of consumers recommending a brand to others, using the Net Promoter Score to gauge brand advocacy. 10. Understanding the Reach of All Branded Communications (TBCA): Assesses the effectiveness and reach of branded communications, providing insights into marketing communication strategies. 11. Understanding Which Brands Are Trying to Improve People''s Lives (Ideals): Investigates consumer perceptions of brands attempting to make a positive impact on society, aligning with consumer values. 12. Understanding Brand Associations to Different Advertising Messages (Ad Messaging): Evaluates consumer associations with specific advertising messages, aiding in refining advertising strategies. 13. Understanding Prompted Needs That Bring People Into the Category at a Category Level (Category Prompted NBS): Identifies needs prompted by external stimuli that lead consumers into a category, helping to understand consumer triggers at a category level. 14. null: The answer cannot be retrieved from the text." },
        { "Which type of unaided awareness question would you like to use?", "Unaided Brand Awareness: This question type asks respondents to name brands they are aware of in a category without any prompts or cues. It measures the top-of-mind awareness and is a good indicator of spontaneous brand recall. - Unaided Brand Awareness - Full Brand Name: Similar to the standard unaided brand awareness question, this version requires respondents to mention the full brand name. It can help assess how well consumers recognize the complete brand identity as opposed to just a part of it. - Unaided Needs-Based Salience (NBS): This type assesses the awareness of brands based on specific needs or occasions, without prompting. It helps understand how well a brand is associated with particular consumer needs or situations. - Unaided Needs-Based Salience (NBS) - Full Brand Name: This variant combines unaided needs-based salience with the requirement to mention the full brand name. It provides insights into both the specific needs associated with the brand and the recognition of the full brand identity. - Prompted Needs-Based Salience (NBS): Unlike unaided versions, this question type prompts respondents with a list of needs or occasions to evaluate how salient a brand is in those contexts. It provides a more guided approach to understanding brand associations with specific needs. - Prompted Needs-Based Salience (NBS) - Full Brand Name: This option combines prompted needs-based salience with the requirement for respondents to identify brands by their full names. It helps in assessing brand salience in particular needs-based contexts with precise brand identity recognition. - No Unaided Awareness Question: This option indicates that no unaided awareness questions will be used in the survey. It might be chosen if the focus is solely on prompted measures or if unaided awareness is not relevant for the study objectives. - null: The answer cannot be retrieved from the text." },
        { "Which version of the Availability question would you like to use?", "1. Mixed: This option refers to a combination of both online and offline methods for assessing availability. It is particularly useful when the target audience is reachable through multiple channels, ensuring a comprehensive understanding of availability across different environments. Mixed Availability can accommodate diverse respondent preferences and logistical constraints, providing a balanced approach for data collection. \n 2. Online: This version focuses solely on the availability of products or services in online environments. It is ideal for projects where digital presence and e-commerce play a significant role in consumer access and engagement. Online Availability emphasizes the assessment of online platforms, digital stores, and web-based services, making it suitable for brands with a strong digital footprint. \n 3. Offline: This option addresses the availability of products or services in physical locations, such as retail stores, local markets, or other offline venues. Offline Availability is essential for understanding how consumers access products in traditional settings, which can be critical for brands that rely on physical store presence. It provides insights into distribution, shelf availability, and in-store promotions." },
        { "Which version of the Familiarity question would you like to use?", "FMCG (Fast-Moving Consumer Goods): This version of the familiarity question is tailored to capture how familiar consumers are with products that are purchased frequently and have a quick turnover. It helps assess consumer recognition and perception of everyday items like groceries or household products. - FMCG with Time Dimension: This option extends the standard FMCG familiarity question by incorporating a time element. It may assess changes in familiarity over time or how recent interactions with the product have influenced consumer awareness. This approach helps in understanding patterns or shifts in consumer recognition related to frequent purchases. - Long-term Purchase / Services: This version focuses on products or services that are purchased infrequently or have a longer lifecycle, such as electronics or financial services. It aims to gauge consumer familiarity with brands in these categories, where purchase decisions are made less often, and brand recognition may develop differently compared to FMCG. - Flexible Familiarity - Dynamic Grid: This approach uses a dynamic grid format to assess familiarity, allowing for greater flexibility in how questions are presented and answered. It can adapt to various types of products and services, making it versatile for capturing nuanced consumer insights across different categories. - Flexible Familiarity - Drag and Drop: Similar to the dynamic grid, this method uses a drag-and-drop interface to collect data on familiarity. This interactive format may engage respondents more effectively and provide insights into their familiarity with brands or products by allowing them to rank or sort items based on their recognition. - null: The answer cannot be retrieved from the text." },
        { "Which version of the market share question would you like to use?", "Last 10 Purchases: This question asks respondents to recall and list the brands they purchased during their last ten buying occasions. It helps in understanding the frequency and variety of brand purchases, providing insights into consumer loyalty and switching behavior. - Share of Last 10: This option focuses on the proportion of the last ten purchases attributed to each brand. It provides a more detailed understanding of brand dominance or the competitive landscape in a consumer''s recent purchase history. - Actual Spend/Usage (Currency): This question captures the actual amount of money spent on each brand in a given period. It provides insights into consumer spending patterns and the financial performance of brands in the market. - Actual Spend/Usage (Units): This version records the actual number of units purchased of each brand. It helps in assessing the volume of products consumed and can be useful in understanding market penetration and consumption trends. - Percentage Spend/Usage: This option asks respondents to estimate the percentage of their total spending or usage attributed to each brand. It provides a relative measure of brand share in terms of consumer expenditure or usage, allowing for a comparison of brand performance. - null: The answer cannot be retrieved from the text." },
        { "Would you like to include the Meaningful Different Salient framework (MDS)?", "The Meaningfully Different Salient (MDS) framework is a brand equity framework used to assess and enhance a brand''s position in the market by evaluating three key dimensions: Meaningful, Different, and Salient. Meaningful: This dimension measures the extent to which consumers perceive a brand as meeting their needs and providing value. A meaningful brand resonates with consumers, often leading to stronger emotional connections and brand loyalty. Different: This dimension assesses how distinct a brand is from its competitors. A brand that stands out in a meaningful way can create a competitive advantage by being perceived as unique or offering something special that others do not. Salient: This dimension evaluates the prominence of a brand in the minds of consumers. A salient brand is one that consumers think of first or are readily aware of in buying situations, which can significantly influence purchase decisions. The MDS framework helps brands understand their current market position and identify areas for improvement to increase their attractiveness and competitiveness. By analyzing these three dimensions, brands can develop strategies to enhance their overall equity and ensure they remain relevant and appealing to consumers.. - null: The answer cannot be retrieved from the text." }
    };

    protected override async Task<List<Entity>> GetRecordsToUpdate()
    {
        var configQuestionsAffected = _replaces
            .Keys
            .ToArray();

        var configQuestionsAIPromptReplaces = _replaces
            .Values
            .ToArray();

        var filter = new FilterExpression
        {
            Conditions = {
                new ConditionExpression("ktr_name", ConditionOperator.In, configQuestionsAffected),
                new ConditionExpression("ktr_aiprompt", ConditionOperator.NotIn, configQuestionsAIPromptReplaces)
            }
        };

        var result = await ReadFromTargetAsync(
            "ktr_configurationquestion",
            ["ktr_configurationquestionid", "ktr_name", "ktr_aiprompt"],
            filter
        );

        return result;
    }

    protected override async Task<MigrationResult> UpdateRecords(List<Entity> configQuestionsToUpdate)
    {
        var fieldToUpdate = "ktr_aiprompt";
        var updateCount = 0;

        foreach (var record in configQuestionsToUpdate)
        {
            var name = record.GetAttributeValue<string>("ktr_name");
            if (_replaces.TryGetValue(name, out var newValue))
            {
                record[fieldToUpdate] = newValue;
                await TargetService.UpdateAsync(record);
                updateCount++;
            }
        }
        var result = MigrationResult.Successful($"Completed: {updateCount} rows processed");
        result.RecordsUpdated = updateCount;
        result.RecordsProcessed = updateCount;

        return result;
    }
}
